ALTER TABLE "landing" FORCE ROW LEVEL SECURITY;
ALTER TABLE "landing_override" FORCE ROW LEVEL SECURITY;
ALTER TABLE "landing_review_carry" FORCE ROW LEVEL SECURITY;
ALTER TABLE "contention" FORCE ROW LEVEL SECURITY;
ALTER TABLE "test_flake" FORCE ROW LEVEL SECURITY;
