import { dirname, normalize } from 'node:path'

type ImportBoundary = {
  name: string
  file: string
  allowed: string[]
  typeOnlyAllowed: string[]
  reason: string
}

const boundary = (
  name: string,
  file: string,
  allowed: string[],
  reason: string,
  typeOnlyAllowed: string[] = [],
): ImportBoundary => ({
  name,
  file,
  allowed: allowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
  typeOnlyAllowed: typeOnlyAllowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
  reason,
})

// Each row lists every import its file may use; anything else fails check-architecture.
// Widen a row deliberately, with its reason still true, rather than routing around it.
export const importBoundaries: ImportBoundary[] = [
  boundary(
    'agent-commands-boundary',
    'orchestrator/src/agent-commands.ts',
    ['./agent-probe.ts', './agent-registry.ts', './args.ts', './db.ts', './local-host.ts'],
    'Keep agent registry command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'canon-budget-boundary',
    'orchestrator/src/canon-budget.ts',
    [],
    'Keep canon budget policy independent of every adapter and store.',
  ),
  boundary(
    'canon-commands-boundary',
    'orchestrator/src/canon-commands.ts',
    [
      'node:fs',
      'node:path',
      'zod',
      './canon.ts',
      './canon-files.ts',
      './canon-hydrate.ts',
      './canon-lint.ts',
      './canon-write-gate.ts',
      './doc/docs.ts',
      './evals.ts',
      './projects.ts',
      '../../shared/ratchet.ts',
    ],
    'Keep canon command adapters independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  boundary(
    'canon-files-boundary',
    'orchestrator/src/canon-files.ts',
    ['node:fs', 'node:path', '../../shared/git.ts', './canon-lint.ts'],
    'Keep canon file collection independent of stores, commands, runs, routing, transports, and worktrees.',
  ),
  boundary(
    'canon-hydrate-boundary',
    'orchestrator/src/canon-hydrate.ts',
    ['node:path', './canon-lint.ts'],
    'Keep canon hydration planning pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'canon-lint-boundary',
    'orchestrator/src/canon-lint.ts',
    [
      'node:path',
      '../../shared/canon-references.ts',
      '../../shared/ratchet.ts',
      './canon-budget.ts',
    ],
    'Keep canon lint decisions pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'canon-write-gate-boundary',
    'orchestrator/src/canon-write-gate.ts',
    ['./canon-lint.ts'],
    'Keep canon write decisions pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'checkout-identity-boundary',
    'orchestrator/src/checkout-identity.ts',
    ['node:fs', 'node:path', './git-environment.ts', './projects.ts'],
    'Keep checkout addressing independent of databases and lifecycle policy.',
  ),
  boundary(
    'cleanup-boundary',
    'orchestrator/src/cleanup/cleanup.ts',
    [
      'node:fs',
      'node:path',
      '../db.ts',
      '../docker-resources.ts',
      '../evidence-query.ts',
      '../git-environment.ts',
      '../project-lock.ts',
      '../projects.ts',
      '../resource-claims.ts',
      '../resource-ownership.ts',
      '../run-authority.ts',
      '../worktree-attribution.ts',
      '../worktree-remove.ts',
      '../worktree-types.ts',
    ],
    'Keep cleanup independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'cleanup-sweep-boundary',
    'orchestrator/src/cleanup/cleanup-sweep.ts',
    [
      'node:fs',
      'node:path',
      './cleanup.ts',
      '../close/close-out.ts',
      '../db.ts',
      '../docker-resources.ts',
      '../hook-tree.ts',
      '../process-liveness.ts',
      '../projects.ts',
      '../resource-ownership.ts',
      '../run-alive.ts',
      '../run-artifacts.ts',
      '../run-authority.ts',
      '../run-lease.ts',
      '../worktree-attribution.ts',
      '../worktree-remove.ts',
      '../worktree-types.ts',
    ],
    'Keep cleanup-sweep independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'clock-boundary',
    'orchestrator/src/clock.ts',
    [],
    'Enforce the clock concern boundary: a primitive that imports nothing.',
  ),
  boundary(
    'close-out-boundary',
    'orchestrator/src/close/close-out.ts',
    [
      'node:fs',
      'node:path',
      './close-out-adoption.ts',
      '../db.ts',
      '../git-environment.ts',
      '../hook-tree.ts',
      '../idle-kill.ts',
      '../keep-tree-hold.ts',
      '../process-liveness.ts',
      '../project-lock.ts',
      '../projects.ts',
      '../reclaim/reclaim.ts',
      '../resource-claims.ts',
      '../resource-ownership.ts',
      '../run-alive.ts',
      '../run-artifacts.ts',
      '../run-lease.ts',
      '../run-process.ts',
      '../worktree.ts',
      '../worktree-attribution.ts',
      '../worktree-remove.ts',
      '../worktree-types.ts',
    ],
    'Keep close-out independent of routing, contracts, transports, reviews, and the CLI.',
  ),
  boundary(
    'confinement-ruling-boundary',
    'orchestrator/src/confinement-ruling.ts',
    [
      'node:fs',
      './confinement.ts',
      './db.ts',
      './git-environment.ts',
      './projects.ts',
      './run-authority.ts',
      './run-liveness.ts',
    ],
    'Keep confinement rulings independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'database-boundary',
    'orchestrator/src/db.ts',
    [
      'bun:sqlite',
      'node:crypto',
      'node:fs',
      'node:path',
      'node:url',
      '../../shared/brand.ts',
      './contention.ts',
      './database-location.ts',
      './migrations.ts',
    ],
    'Enforce the database concern boundary.',
  ),
  boundary(
    'dispatch-commands-boundary',
    'orchestrator/src/dispatch/dispatch-commands.ts',
    [
      'node:fs',
      './dispatch-preflight.ts',
      '../jobs.ts',
      '../keep-tree-hold.ts',
      '../projects.ts',
      '../failover.ts',
      '../mcp-preflight.ts',
    ],
    'Keep dispatch command adapters independent of transports, routing, worktrees, the CLI, and reviews.',
  ),
  boundary(
    'dispatch-preflight-boundary',
    'orchestrator/src/dispatch/dispatch-preflight.ts',
    [
      '../args.ts',
      '../checkout-identity.ts',
      '../db.ts',
      '../git-environment.ts',
      '../jobs.ts',
      '../lens/lenses.ts',
      '../projects.ts',
      '../review-target.ts',
      '../worktree-caller.ts',
      '../worktree-preflight.ts',
      '../worktree-template.ts',
    ],
    'Keep dispatch admission independent of transports, routing, and contracts.',
  ),
  boundary(
    'doc-commands-boundary',
    'orchestrator/src/doc/doc-commands.ts',
    ['node:fs', '../canon.ts', './docs.ts'],
    'Keep doc commands independent of database writes beyond docs, runs, routing, transports, and the CLI.',
  ),
  boundary(
    'doc-write-allowed-boundary',
    'orchestrator/src/doc/doc-write-allowed.ts',
    ['../canon-hydrate.ts', '../canon-write-gate.ts', '../pack-budget.ts', '../canon-lint.ts'],
    'Keep document write decisions independent of stores, HTTP, filesystems, and CLI.',
  ),
  boundary(
    'doctor-boundary',
    'orchestrator/src/doctor.ts',
    [
      'node:fs',
      './agent-auth.ts',
      './agent-registry.ts',
      './agents.ts',
      './agreement.ts',
      './db.ts',
      './docker-resources.ts',
      './evidence-query.ts',
      './keep-tree-hold.ts',
      './local-host.ts',
      './resource-claims.ts',
      './resource-ownership.ts',
      './score/score.ts',
      './worktree-attribution.ts',
      './worktree-lifecycle.ts',
      './canon.ts',
      './doc/docs.ts',
      './pack-budget.ts',
      './evals.ts',
      './sandbox.ts',
      './migrations.ts',
      './health.ts',
      './projects.ts',
    ],
    'Keep doctor independent of transports, routing, run control, the CLI, and reviews by value.',
  ),
  boundary(
    'duel-boundary',
    'orchestrator/src/duel.ts',
    ['./db.ts', './evidence-query.ts', './score/score.ts'],
    'Enforce the duel concern boundary.',
  ),
  boundary(
    'epic-commands-boundary',
    'orchestrator/src/epic/epic-commands.ts',
    ['./epic.ts'],
    'Keep epic command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'evidence-query-boundary',
    'orchestrator/src/evidence-query.ts',
    ['./db.ts', './failure/failure.ts', './hook-tree.ts', 'bun:sqlite'],
    'Enforce the evidence-query concern boundary.',
  ),
  boundary(
    'failover-boundary',
    'orchestrator/src/failover.ts',
    [
      './agent-registry.ts',
      './db.ts',
      'bun:sqlite',
      './keep-tree-hold.ts',
      './mcp-preflight.ts',
      './resume-tree.ts',
    ],
    'Keep failover independent of execution transports, contracts, and worktrees.',
  ),
  boundary(
    'failure-commands-boundary',
    'orchestrator/src/failure/failure-commands.ts',
    ['../db.ts', './failure.ts', '../run-authority.ts'],
    'Keep failure command adapters independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  boundary(
    'git-environment-boundary',
    'orchestrator/src/git-environment.ts',
    ['node:crypto', 'node:fs', 'node:os', 'node:path', '../../shared/git.ts'],
    'Keep hermetic git observation independent of lifecycle and policy concerns.',
  ),
  boundary(
    'health-commands-boundary',
    'orchestrator/src/health-commands.ts',
    ['../../shared/orch-contract.ts', './db.ts', './health.ts'],
    'Keep health command adapters independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  boundary(
    'isolation-boundary',
    'orchestrator/src/worktree.ts',
    [
      'node:fs',
      './worktree-create.ts',
      './worktree-readonly.ts',
      './projects.ts',
      './worktree-types.ts',
    ],
    'Keep the isolation module independent of run policy and lifecycle concerns.',
  ),
  boundary(
    'issue-report-fields-boundary',
    'orchestrator/src/issue/issue-report-fields.ts',
    [],
    'Keep issue report field decisions pure and independent of adapters.',
  ),
  boundary(
    'job-commands-boundary',
    'orchestrator/src/job-commands.ts',
    ['./jobs.ts'],
    'Keep job catalogue command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'judgement-boundary',
    'orchestrator/src/judgement.ts',
    [
      'node:fs',
      '../../shared/record/schema.ts',
      './db.ts',
      './duel.ts',
      './jobs.ts',
      './machine-identity.ts',
      './record-api-client.ts',
      './review.ts',
      './review-outbox.ts',
      './review-triage.ts',
      './review-vocabulary.ts',
      './run-authority.ts',
      './run-outbox.ts',
      './score/score.ts',
    ],
    'Keep judgement independent of transports, worktrees, routing, the CLI, durable execution, dispatch, and cleanup.',
  ),
  boundary(
    'landing-outbox-boundary',
    'orchestrator/src/landing-outbox.ts',
    ['../../shared/record/schema.ts', 'bun:sqlite'],
    'Enforce the landing-outbox concern boundary.',
  ),
  boundary(
    'machine-identity-boundary',
    'orchestrator/src/machine-identity.ts',
    ['node:os', '../../shared/record/schema.ts', './db.ts'],
    'Enforce the machine-identity concern boundary.',
  ),
  boundary(
    'mcp-commands-boundary',
    'orchestrator/src/mcp-commands.ts',
    ['./mcp.ts'],
    'Keep MCP command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'mcp-preflight-boundary',
    'orchestrator/src/mcp-preflight.ts',
    ['./agent-registry.ts', './jobs.ts', './projects.ts', './run-process.ts'],
    'Keep MCP preflight independent of execution, transport, routing, and mutation.',
    ['./contract/contract.ts'],
  ),
  boundary(
    'metric-commands-boundary',
    'orchestrator/src/metric/metric-commands.ts',
    ['./metric.ts'],
    'Keep metric command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'monitor-commands-boundary',
    'orchestrator/src/monitor/monitor-commands.ts',
    [
      'node:crypto',
      'node:fs',
      'node:path',
      '../../../shared/monitor-capability.ts',
      '../db.ts',
      '../evals.ts',
      './monitor.ts',
      './monitor-notices.ts',
      '../process-liveness.ts',
      './monitor-types.ts',
    ],
    'Keep monitor command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'port-commands-boundary',
    'orchestrator/src/porting/port-commands.ts',
    ['node:fs', 'node:path', '../db.ts', './porting.ts', './porting-import.ts', '../projects.ts'],
    'Keep port commands independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  boundary(
    'postgres-schema-auth-boundary',
    'shared/record/schema-auth.ts',
    ['drizzle-orm/pg-core', './schema.ts'],
    'Enforce the Better Auth schema concern boundary.',
  ),
  boundary(
    'postgres-schema-docs-boundary',
    'shared/record/schema-docs.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted doc schema concern boundary.',
  ),
  boundary(
    'postgres-schema-hub-boundary',
    'shared/record/schema-hub.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted hub evidence schema concern boundary.',
  ),
  boundary(
    'postgres-schema-landing-boundary',
    'shared/record/schema-landing.ts',
    ['drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted landing schema concern boundary.',
  ),
  boundary(
    'postgres-schema-review-boundary',
    'shared/record/schema-review.ts',
    ['drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted review schema concern boundary.',
  ),
  boundary(
    'postgres-schema-run-boundary',
    'shared/record/schema-run.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted run schema concern boundary.',
  ),
  boundary(
    'postgres-schema-snapshots-boundary',
    'shared/record/schema-snapshots.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted orchestrator snapshot schema concern boundary.',
  ),
  boundary(
    'process-liveness-boundary',
    'orchestrator/src/process-liveness.ts',
    ['../../shared/process-identity.ts'],
    'Enforce the process-liveness concern boundary: an OS primitive that imports nothing of ours.',
  ),
  boundary(
    'project-commands-boundary',
    'orchestrator/src/project-commands.ts',
    [
      'node:fs',
      './db.ts',
      './lens/lenses.ts',
      './projects.ts',
      './worktree-lifecycle.ts',
      './worktree-template.ts',
    ],
    'Keep project commands independent of runs, routing, transports, reviews, the CLI, and worktrees by value.',
  ),
  boundary(
    'prompt-retarget-boundary',
    'orchestrator/src/prompt-retarget.ts',
    ['./checkout-identity.ts'],
    'Keep prompt retargeting independent of database, transport, contract, and routing concerns.',
  ),
  boundary(
    'recalibration-boundary',
    'orchestrator/src/recalibration.ts',
    [
      'node:fs',
      'node:readline/promises',
      './agreement.ts',
      './db.ts',
      './jobs.ts',
      './score/score.ts',
      'node:stream',
    ],
    'Keep recalibration independent of transports, worktrees, routing, the CLI, durable execution, dispatch, and cleanup.',
  ),
  boundary(
    'recipe-lifecycle-boundary',
    'orchestrator/src/recipe/recipe-lifecycle.ts',
    ['./recipe-schema.ts', './recipe-step.ts'],
    'Keep lifecycle planning pure and independent of execution, persistence, filesystem, and the register.',
  ),
  boundary(
    'recipe-loader-boundary',
    'orchestrator/src/recipe/recipe-loader.ts',
    ['node:fs', 'node:path', './recipe-schema.ts'],
    'Keep tracked recipe loading independent of execution, persistence, and CLI concerns.',
  ),
  boundary(
    'recipe-schema-boundary',
    'orchestrator/src/recipe/recipe-schema.ts',
    ['zod'],
    'Keep the recipe schema pure and independent of file, register, and execution concerns.',
  ),
  boundary(
    'recipe-step-boundary',
    'orchestrator/src/recipe/recipe-step.ts',
    ['node:path', '../worktree-template.ts', './recipe-schema.ts'],
    'Keep recipe step execution independent of lifecycle, persistence, claims, and register concerns.',
  ),
  boundary(
    'record-api-boundary',
    'orchestrator/src/record-api.ts',
    [
      'hono',
      'hono/cors',
      'zod',
      './record-auth.ts',
      './record-docs.ts',
      './record-snapshots.ts',
      './record-verdicts.ts',
      './record-projects.ts',
      './record-runs.ts',
    ],
    'Enforce the record-api concern boundary.',
  ),
  boundary(
    'record-api-client-boundary',
    'orchestrator/src/record-api-client.ts',
    [
      './doc/doc-write-allowed.ts',
      './record-auth.ts',
      './record-session.ts',
      './record-snapshots.ts',
    ],
    'Enforce the record API client concern boundary.',
  ),
  boundary(
    'record-api-server-boundary',
    'orchestrator/src/record-api-server.ts',
    [
      './postgres/postgres-migrate.ts',
      './record-api.ts',
      './record-auth.ts',
      './record-docs.ts',
      './record-projects.ts',
      './record-reviews.ts',
      './record-runs.ts',
      './record-snapshots.ts',
      './record-verdicts.ts',
    ],
    'Enforce the record-api-server concern boundary.',
  ),
  boundary(
    'record-auth-boundary',
    'orchestrator/src/record-auth.ts',
    [
      '@better-auth/drizzle-adapter/relations-v2',
      'better-auth',
      'better-auth/plugins',
      'bun',
      'drizzle-orm/bun-sql',
      '../../shared/record/schema.ts',
      '../../shared/record/schema-auth.ts',
    ],
    'Enforce the record-auth concern boundary.',
  ),
  boundary(
    'record-auth-command-boundary',
    'orchestrator/src/record-auth-command.ts',
    ['../../shared/record-session.ts', './record-auth.ts', './record-session.ts'],
    'Enforce the record-auth-command concern boundary.',
  ),
  boundary(
    'record-cache-boundary',
    'orchestrator/src/record-cache.ts',
    ['./db.ts', './record-api-client.ts', 'bun:sqlite'],
    'Enforce the record-cache concern boundary.',
  ),
  boundary(
    'record-docs-boundary',
    'orchestrator/src/record-docs.ts',
    ['bun', '../../shared/record/schema.ts', './doc/doc-write-allowed.ts'],
    'Enforce the record-docs concern boundary.',
  ),
  boundary(
    'record-projects-boundary',
    'orchestrator/src/record-projects.ts',
    ['bun'],
    'Keep hosted project record access isolated from other production modules.',
  ),
  boundary(
    'record-publish-boundary',
    'orchestrator/src/record-publish.ts',
    [
      './agent-commands.ts',
      './health-commands.ts',
      './job-commands.ts',
      './machine-identity.ts',
      './record-api-client.ts',
      './record-snapshots.ts',
      './serve.ts',
    ],
    'Enforce that snapshot publishing composes only the existing view services and record client.',
  ),
  boundary(
    'record-push-docs-boundary',
    'orchestrator/src/record-push-docs.ts',
    ['./db.ts', './record-api-client.ts', './doc/doc-write-allowed.ts'],
    'Enforce the record-push-docs concern boundary.',
  ),
  boundary(
    'record-reviews-boundary',
    'orchestrator/src/record-reviews.ts',
    ['bun', './record-runs.ts'],
    'Keep hosted review record access limited to the hosted run record contract.',
  ),
  boundary(
    'record-runs-boundary',
    'orchestrator/src/record-runs.ts',
    ['bun'],
    'Enforce the record-runs concern boundary.',
  ),
  boundary(
    'record-snapshots-boundary',
    'orchestrator/src/record-snapshots.ts',
    ['bun', '../../shared/record/schema.ts'],
    'Enforce the hosted snapshot service concern boundary.',
  ),
  boundary(
    'record-sync-boundary',
    'orchestrator/src/record-sync.ts',
    [
      'bun',
      'drizzle-orm/bun-sql',
      '../../shared/record/schema.ts',
      '../../shared/record/schema-landing.ts',
      '../../shared/record/schema-review.ts',
      '../../shared/record/schema-run.ts',
      './db.ts',
      './landing-outbox.ts',
      './machine-identity.ts',
      './record-cache.ts',
      './record-session.ts',
      './review-outbox.ts',
      './run-outbox.ts',
      './score/score-outbox.ts',
      'bun:sqlite',
    ],
    'Enforce the record-sync concern boundary.',
  ),
  boundary(
    'record-sync-command-boundary',
    'orchestrator/src/record-sync-command.ts',
    ['./record-sync.ts'],
    'Enforce the record-sync-command concern boundary.',
  ),
  boundary(
    'record-verdicts-boundary',
    'orchestrator/src/record-verdicts.ts',
    ['bun', './score/score.ts'],
    'Enforce the record-verdicts concern boundary.',
  ),
  boundary(
    'resource-ownership-boundary',
    'orchestrator/src/resource-ownership.ts',
    [
      'node:fs',
      'node:path',
      './checkout-identity.ts',
      './database-location.ts',
      './db.ts',
      './docker-resources.ts',
      './evidence-query.ts',
      './git-environment.ts',
      './process-liveness.ts',
      './project-lock.ts',
      './run-alive.ts',
      './run-lease.ts',
      'bun:sqlite',
    ],
    'Enforce the resource-ownership concern boundary.',
  ),
  boundary(
    'review-commands-boundary',
    'orchestrator/src/review-commands.ts',
    [
      'bun:sqlite',
      'node:fs',
      'zod',
      './db.ts',
      './git-environment.ts',
      './jobs.ts',
      './projects.ts',
      './review.ts',
      './review-calibration.ts',
      './review-coverage.ts',
      './review-evidence-sql.ts',
      './review-pins.ts',
      './review-tier.ts',
      './review-triage.ts',
      './review-vocabulary.ts',
      './review-yield.ts',
    ],
    'Keep review commands independent of runs, transports, routing by value, the CLI, and worktrees by value.',
  ),
  boundary(
    'review-outbox-boundary',
    'orchestrator/src/review-outbox.ts',
    ['../../shared/record/schema.ts', './db.ts', 'bun:sqlite'],
    'Enforce the review-outbox concern boundary.',
  ),
  boundary(
    'review-target-boundary',
    'orchestrator/src/review-target.ts',
    ['node:path', './git-environment.ts', './projects.ts', './worktree-caller.ts'],
    'Keep review-target resolution independent of execution and mutation concerns.',
  ),
  boundary(
    'review-vocabulary-boundary',
    'orchestrator/src/review-vocabulary.ts',
    [],
    'Enforce the review-vocabulary concern boundary.',
  ),
  boundary(
    'routing-commands-boundary',
    'orchestrator/src/routing-commands.ts',
    [
      './agreement.ts',
      './duel.ts',
      './guide.ts',
      './lens/lenses.ts',
      './projects.ts',
      './route.ts',
      './routing-backtest.ts',
    ],
    'Keep routing command adapters independent of runs, transports, the CLI, worktrees, and reviews by value.',
  ),
  boundary(
    'run-answer-boundary',
    'orchestrator/src/run-answer.ts',
    [
      'node:fs',
      './agent-registry.ts',
      './args.ts',
      './clock.ts',
      './contract/contract.ts',
      './db.ts',
      './failover.ts',
      './jobs.ts',
      './keep-tree-hold.ts',
      './mcp-preflight.ts',
      './outcome.ts',
      './process-liveness.ts',
      './run.ts',
      './run-artifacts.ts',
      './run-authority.ts',
      './run-control.ts',
      './run-dispatch.ts',
      './git-environment.ts',
    ],
    'Keep run-answer independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-artifacts-boundary',
    'orchestrator/src/run-artifacts.ts',
    [
      'node:fs',
      'node:path',
      './artifact-paths.ts',
      './database-location.ts',
      './db.ts',
      './migrations.ts',
      './resource-ownership.ts',
    ],
    'Keep run artifacts independent of routing, contracts, transports, reviews, and isolation.',
  ),
  boundary(
    'run-authority-boundary',
    'orchestrator/src/run-authority.ts',
    ['./db.ts', 'bun:sqlite'],
    'Enforce the run-authority concern boundary.',
  ),
  boundary(
    'run-control-boundary',
    'orchestrator/src/run-control.ts',
    [
      'node:fs',
      './args.ts',
      './clock.ts',
      './collect/collect.ts',
      './db.ts',
      './events.ts',
      './failover.ts',
      './git-environment.ts',
      './mcp-preflight.ts',
      './outcome.ts',
      './projects.ts',
      './resume-tree.ts',
      './run.ts',
      './run-authority.ts',
      './run-dispatch.ts',
      './run-liveness.ts',
      './checkpoint.ts',
    ],
    'Keep run-control independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-diff-boundary',
    'orchestrator/src/run-diff.ts',
    ['node:fs', './db.ts', './git-environment.ts', './projects.ts'],
    'Keep run diff independent of run control, transports, routing, the CLI, and worktrees by value.',
  ),
  boundary(
    'run-dispatch-boundary',
    'orchestrator/src/run-dispatch.ts',
    [
      'node:child_process',
      'node:crypto',
      'node:fs',
      './db.ts',
      './dispatch/dispatch-preflight.ts',
      './jobs.ts',
      './mcp-preflight.ts',
      './projects.ts',
      './run.ts',
      './run-artifacts.ts',
      './failover.ts',
    ],
    'Keep run-dispatch independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-inbox-boundary',
    'orchestrator/src/run-inbox.ts',
    ['./db.ts', './evidence-query.ts', './projects.ts'],
    'Keep run inbox independent of run control, transports, routing, the CLI, and worktrees.',
  ),
  boundary(
    'run-listing-boundary',
    'orchestrator/src/run-listing.ts',
    [
      './collect/collect.ts',
      './db.ts',
      './evidence-query.ts',
      './outcome.ts',
      './events.ts',
      './idle-kill.ts',
    ],
    'Keep run listing independent of run control, transports, routing, the CLI, and worktrees.',
  ),
  boundary(
    'run-liveness-boundary',
    'orchestrator/src/run-liveness.ts',
    [
      './db.ts',
      './process-liveness.ts',
      './resource-ownership.ts',
      './run-alive.ts',
      './run-authority.ts',
      './run-lease.ts',
      'bun:sqlite',
    ],
    'Enforce the run-liveness concern boundary.',
  ),
  boundary(
    'run-outbox-boundary',
    'orchestrator/src/run-outbox.ts',
    ['../../shared/record/schema.ts', './hook-tree.ts', 'bun:sqlite'],
    'Enforce the run-outbox concern boundary.',
  ),
  boundary(
    'run-process-boundary',
    'orchestrator/src/run-process.ts',
    [
      'node:crypto',
      './checkpoint.ts',
      './db.ts',
      './dispatch/dispatch-preflight.ts',
      './idle-kill.ts',
      './agent-registry.ts',
    ],
    'Keep run process control independent of routing, contracts, reviews, and transports.',
  ),
  boundary(
    'run-stop-boundary',
    'orchestrator/src/run-stop.ts',
    [
      './cleanup/cleanup.ts',
      './db.ts',
      './resource-ownership.ts',
      './run-authority.ts',
      './run-liveness.ts',
      './worktree-remove.ts',
      './worktree-types.ts',
    ],
    'Keep run-stop independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'score-boundary',
    'orchestrator/src/score/score.ts',
    [],
    'Enforce the score concern boundary.',
  ),
  boundary(
    'store-hooks-boundary',
    'orchestrator/src/store-hooks.ts',
    ['./db.ts', './evidence-query.ts', './run-liveness.ts', './workflow/workflow-seeds.ts'],
    'Enforce the store-hooks concern boundary.',
  ),
  boundary(
    'task-branch-boundary',
    'orchestrator/src/task-branch.ts',
    [
      './checkout-identity.ts',
      './db.ts',
      './git-environment.ts',
      './merged-pull-request.ts',
      './projects.ts',
      './review-evidence-sql.ts',
      './branch/branch-state.ts',
      './worktree-types.ts',
    ],
    'Keep task branch identity independent of transports, contracts, and routing.',
  ),
  boundary(
    'workflows-boundary',
    'orchestrator/src/workflow/workflow-seeds.ts',
    ['../db.ts', '../review-vocabulary.ts', 'bun:sqlite'],
    'Keep workflow seeds dependent only on database transactions and review vocabulary.',
  ),
  boundary(
    'worktree-attribution-boundary',
    'orchestrator/src/worktree-attribution.ts',
    [
      'node:fs',
      'node:path',
      './checkout-identity.ts',
      './database-location.ts',
      './db.ts',
      './git-environment.ts',
      './worktree-types.ts',
    ],
    'Keep attribution and extraction independent of lifecycle policy and transports.',
    ['./worktree.ts'],
  ),
  boundary(
    'worktree-mcp-boundary',
    'orchestrator/src/worktree-mcp.ts',
    ['node:fs', 'node:path'],
    'Keep worker MCP file provisioning independent of lifecycle and policy.',
  ),
  boundary(
    'worktree-template-boundary',
    'orchestrator/src/worktree-template.ts',
    [],
    'Keep template grammar independent of execution, lifecycle, and policy.',
  ),
]
