import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { attributionFindings } from '../../../shared/attribution-markers.ts'
import { sourcedAttributionFindings } from './check-attribution.ts'

const fixture = JSON.parse(
  readFileSync(join(import.meta.dir, 'fixtures/attribution-cases.json'), 'utf8'),
) as { blocked: string[]; allowed: string[] }

describe('attribution marker fixtures', () => {
  test('every attribution marker class is blocked', () => {
    for (const text of fixture.blocked) expect(attributionFindings(text)).toHaveLength(1)
  })

  test('ordinary Claude and AI discussion passes', () => {
    for (const text of fixture.allowed) expect(attributionFindings(text)).toEqual([])
  })

  test('findings retain their source, line, and complete offending line', () => {
    expect(sourcedAttributionFindings('abc123', 'ordinary\nGenerated by AI\n')).toEqual([
      { source: 'abc123', line: 2, text: 'Generated by AI' },
    ])
  })
})
