import { Database } from 'bun:sqlite'
import { describe, expect, test } from 'bun:test'
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  writeFileSync,
} from 'node:fs'
import { join, resolve } from 'node:path'
import { dir } from '../../test/preload.ts'
import { applyMigrations } from '../database/migrations.ts'
import type { ProjectSettings } from '../project/projects.ts'

const cli = resolve(import.meta.dir, '../cli/orch.ts')

function run(database: string, ...argv: string[]) {
  return Bun.spawnSync(['bun', '--no-env-file', cli, 'check', '--enabled', ...argv], {
    env: { ...process.env, ORCH_DB: database },
    stdin: 'ignore',
    stdout: 'pipe',
    stderr: 'pipe',
  })
}

function registerProject(name: string, path: string, settings: ProjectSettings): string {
  const databasePath = join(mkdtempSync(join(dir, 'enabled-check-db-')), 'orch.db')
  const database = new Database(databasePath, { create: true })
  applyMigrations(database)
  database
    .query('INSERT INTO project (name,path,settings) VALUES (?,?,?)')
    .run(name, path, JSON.stringify(settings))
  database.close()
  return databasePath
}

function git(root: string, ...argv: string[]) {
  const result = Bun.spawnSync(['git', ...argv], { cwd: root, stdout: 'pipe', stderr: 'pipe' })
  if (result.exitCode !== 0) throw new Error(result.stderr.toString())
}

function repository(name: string): string {
  const root = mkdtempSync(join(dir, `${name}-`))
  git(root, 'init', '-b', 'main')
  git(root, 'config', 'user.name', 'Fixture')
  git(root, 'config', 'user.email', 'fixture@example.test')
  writeFileSync(join(root, 'README.md'), 'ordinary text\n')
  git(root, 'add', 'README.md')
  git(root, 'commit', '-m', 'Initial fixture')
  git(root, 'update-ref', 'refs/remotes/origin/main', 'HEAD')
  return root
}

function installTypos(): string {
  const bin = mkdtempSync(join(dir, 'enabled-check-bin-'))
  const typos = join(bin, 'typos')
  writeFileSync(
    typos,
    '#!/bin/sh\nif [ "$1" = "--version" ]; then echo "typos-cli 1.50.0"; exit 0; fi\npwd > "$CHECK_SENTINEL"\n',
  )
  chmodSync(typos, 0o755)
  return bin
}

describe('orch check --enabled', () => {
  test('an empty register opt-in succeeds and names the project', () => {
    const root = repository('checks-none')
    const database = registerProject('checks-none', root, { trunk: 'main' })

    const result = run(database, '--project', 'checks-none')

    expect({ exitCode: result.exitCode, stderr: result.stderr.toString() }).toEqual({
      exitCode: 0,
      stderr: '',
    })
    expect(result.stdout.toString().trim()).toBe('no checks enabled for checks-none')
  })

  test('a spelling-only opt-in runs typos', () => {
    const root = repository('checks-spelling')
    const bin = installTypos()
    const sentinel = join(root, 'typos-ran')
    const worktree = join(root, '.claude', 'worktrees', 'checks-spelling')
    mkdirSync(join(root, '.claude', 'worktrees'), { recursive: true })
    git(root, 'worktree', 'add', '-b', 'checks-spelling-worktree', worktree)
    const database = registerProject('checks-spelling', root, {
      trunk: 'main',
      checks: { spelling: true },
    })

    const result = Bun.spawnSync(
      ['bun', '--no-env-file', cli, 'check', '--enabled', '--project', 'checks-spelling'],
      {
        env: {
          ...process.env,
          ORCH_DB: database,
          PATH: `${bin}:${process.env.PATH}`,
          CHECK_SENTINEL: sentinel,
        },
        cwd: worktree,
        stdin: 'ignore',
        stdout: 'pipe',
        stderr: 'pipe',
      },
    )

    expect(result.exitCode).toBe(0)
    expect(existsSync(sentinel)).toBe(true)
    expect(readFileSync(sentinel, 'utf8').trim()).toBe(realpathSync(worktree))
  })

  test('both opt-ins run and name the failing check', () => {
    const root = repository('checks-both')
    const bin = installTypos()
    const sentinel = join(root, 'typos-ran')
    git(root, 'commit', '--allow-empty', '-m', 'Generated by AI')
    const database = registerProject('checks-both', root, {
      trunk: 'main',
      checks: { spelling: true, attribution: true },
    })

    const result = Bun.spawnSync(
      ['bun', '--no-env-file', cli, 'check', '--enabled', '--project', 'checks-both'],
      {
        env: {
          ...process.env,
          ORCH_DB: database,
          PATH: `${bin}:${process.env.PATH}`,
          CHECK_SENTINEL: sentinel,
        },
        stdin: 'ignore',
        stdout: 'pipe',
        stderr: 'pipe',
      },
    )

    expect(result.exitCode).toBe(1)
    expect(existsSync(sentinel)).toBe(true)
    expect(result.stdout.toString()).toContain('Generated by AI')
    expect(result.stdout.toString()).toContain('failed check: attribution')
    expect(result.stdout.toString()).not.toContain('failed check: spelling')
  })
})
