import { PLATFORM_SLUG } from '../../shared/brand.ts'

const DUPLICATE_TITLE_FIXTURE_RAW = {
  "DEV-209": "[DEFECT] `orch runs --json` emits one JSON object per line (JSONL), so a caller doing a single JSON.parse / json.load over the whole stream fails with \"Extra data: line 2\". Each line parses correctly on its own, so the output is well-formed JSONL rather than broken JSON. The larger finding is that orch's --json flags are not consistent with each other: hooks/session-brief.py does json.loads over the ENTIRE output of `orch inbox --all --json` and expects a Python list, which means that command returns a single array. Two --json flags on the same binary, two different shapes, nothing saying which is which.",
  "DEV-210": "[DEFECT] `orch runs --json` emits JSONL — one JSON object per line — while other orch JSON surfaces emit a single JSON document. A caller doing one `JSON.parse` over the whole stream fails. Measured on 2026-09-04 from the __PLATFORM__ checkout on main at 5cbe927: `./bin/orch runs --json | python3 -c 'import json,sys; json.load(sys.stdin)'` raises `json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 889)`, over 1142 lines; the first line parses cleanly on its own as an object. By contrast `./bin/orch project list --json` returns a JSON array parsed by a single `json.load`, and `./bin/orch state --days 1` returns a single object (`{\"live\":[...],...}`). So the inconsistency is across the `--json` surface, not a property of one command.\n\nReported by a __PLATFORM__ session (__PLATFORM__-65) that hit it while writing a consumer, and re-measured independently here. That session notes the framing that led it astray: orchestrator/CLAUDE.md lists `orch runs --json` as \"the run list, with cwd and session id\" directly beneath `orch state [--days N]` described as \"the whole payload\", which reads as though both return one JSON document.",
  "DEV-265": "[DEFECT] The review-recording path shipped by DEV-195 (`orch review record` → `orch review triage` → `orch review complete`, feeding per-lens calibration) has never been exercised. The live orch.db has zero rows in `review`, `review_lens` and `review_finding`, while ~200 review-lens runs exist and were scored. Two sessions ran a dozen-plus lenses today and recorded none; one did not know the step existed as distinct from scoring. Nothing in the dispatch or scoring path points at it: `orch result` for a review-lens run prints the score-it line and not a record-it line, the Stop hook nags for unscored runs but not unrecorded reviews, and calibration (which reads review_lens) has therefore always been empty.",
  "DEV-266": "[DEFECT] The review-recording workflow shipped, was documented, and has never once been used. The `review`, `review_lens` and `review_finding` tables are ALL EMPTY.\n\nFound by another session while migrating a copy of the live orchestrator database for unrelated work. Every review-lens run ever dispatched on this machine — hundreds, going back weeks — was dispatched, read and SCORED, and none was ever passed through `orch review record <lens-run-ids>` → triage each finding → `orch review complete <review-id>`.\n\nDEV-195 landed that discipline: per-lens precision, recorded reviews, calibration keyed by lens and runner. The calibration it enables is real and has been cited in this project's own reasoning — a session was reported as reading its calibration line to judge whether an efficiency lens returning zero findings was credible. But the data those figures would be computed from was never written, because the recording step is separate from scoring and nobody performs it.\n\nI am a case in point. I have dispatched roughly a dozen review lenses today, read every one, and scored every one. I recorded none, and did not know `orch review record` was a distinct step rather than something `orch score` implied.\n\nThis is the same shape as three other things found today: the heartbeat script that landed and that nothing arms; canon naming a file nobody had committed; and a monitor reporting a label rather than detecting a condition. A mechanism that exists, is documented, and is not in the path anyone actually walks.\n\nIt surfaced now because DEV-255 is about to make recorded reviews load-bearing — `orch land` will refuse a fast-forward unless a completed review's lenses all measured the tree being landed. On the day that lands, nothing in the database satisfies it.",
  "DEV-293": "[DEFECT] One orchestrator test fails in every review-lens worktree and passes on the main checkout: `orchestrator/src/orch.test.ts:507`, the landing-status assertion, \"expects a resolved ref suffix that git did not report\" / \"landingStatus omits the expected resolved-ref suffix\". Reported independently by four lens runs on four different branches (1721 on DEV-258, 1756 on DEV-257, 1769/1770 on DEV-254, 1786/1787 on the fix deltas), each as \"1 pre-existing unrelated failure\" that stops `bun run check` before the hub/web stages. It reproduced at both parent and tip of DEV-257 (647c587 and 2029316), so it is not caused by any of those branches. It did not reproduce for __PLATFORM__-f1 on trunk under FORCE_COLOR=1 (571/0), and my three gated landings (57eb7d6, 164aa7f, f31a3f5) ran `bun run check` green inside `orch land`.",
  "DEV-294": "The stale-ref-lock status test fails in fresh worktrees and passes in main checkouts, so orch land fails nondeterministically and every worker is told to ignore it",
  "DEV-251": "[SUGGESTION] DEV-240 landed the heartbeat script, and nothing loads or arms it. The mechanism is now: a model reads a sentence in CLAUDE.md and decides to act on it.\n\nVerified by session claude-98 after landing (main 00bfaa1, four post-landing checks clean). It confirmed the landed artifact actually RUNS from the canon path rather than trusting the file's presence — exit 0 with silence for CLEAR, and stubbed runs proving the other two branches emit \"WAITING - 1 run(s) ... 9001/implement codex running\" and \"BLOCKED - 1 question(s) waiting on you\". The artifact is real and all three states work.\n\nBut the five configured hooks are block-agent (PreToolUse and SubagentStart), no-attribution (Bash), score-reminder (Stop) and session-brief (SessionStart), and none references the heartbeat. Outside global CLAUDE.md, the only mention of `orch-heartbeat` anywhere is the script itself.\n\nSo the failure has moved rather than closed: from \"canon names a file that does not exist\" to \"canon names a file that exists and may never be armed\". starship-5f armed it twice believing it had a watcher and had none — that is what the first version of this failure looked like, and the second version is indistinguishable from the outside.\n\nThis is the third instance today of an absence being read as a pass. Round six's dead review lens emitted `findings: []` that read as a clean review; canon named a file that did not exist; and now a watcher that may never be armed. The first two were found by accident."
} as const


export const DUPLICATE_TITLE_FIXTURE = Object.fromEntries(
  Object.entries(DUPLICATE_TITLE_FIXTURE_RAW)
    .map(([key, title]) => [key, title.replaceAll('__PLATFORM__', PLATFORM_SLUG)]),
) as Record<keyof typeof DUPLICATE_TITLE_FIXTURE_RAW, string>

