import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { PLATFORM_SLUG } from '../../../shared/brand.ts'
import {
  createMemoryRecordApiClient,
  installRecordApiClient,
} from '../../test/fixtures/record-api.ts'
import { USER_CANON_MANAGED_MARKER } from '../canon/user-canon-home.ts'
import { db } from '../database/db.ts'
import { setDoc } from '../doc/docs.ts'
import { tryKernelLease } from '../project/project-lock.ts'
import { serializeOwnedSettings } from './settings.ts'
import { applyMachineSettings, printMachineSettingsApplyResults } from './settings-machine-apply.ts'
import { withMachineBoardHooks } from './settings-machine-hooks.ts'
import { applySettingsWrite } from './settings-write.ts'

const OWNER = '01990000-0000-7000-8000-000000000001'
const CANON_BODY =
  '---\ndescription: Personal operating rule\nalways: true\n---\n\n# Personal\n\nKeep this rule.\n'
let root = ''
let environment: NodeJS.ProcessEnv
let pulls = 0

beforeEach(async () => {
  root = mkdtempSync(join(tmpdir(), 'settings-machine-apply-'))
  mkdirSync(join(root, '.claude'))
  mkdirSync(join(root, '.codex'))
  environment = {
    HOME: root,
    BOTTEGA_STATE_HOME: join(root, 'state'),
    CODEX_HOME: join(root, '.codex'),
  }
  pulls = 0
  installRecordApiClient(createMemoryRecordApiClient())
  await setDoc({
    scope: 'settings',
    subject: null,
    owner: OWNER,
    slug: 'settings',
    title: 'settings',
    body: serializeOwnedSettings({
      permissions: { allow: ['Bash(orch *)'] },
      hooks: {},
      envKeys: [],
    }),
    delivery: 'demand',
    reason: 'fixture settings',
  })
  await setDoc({
    scope: 'canon',
    subject: null,
    owner: OWNER,
    slug: 'AGENTS.md',
    title: 'AGENTS.md',
    body: CANON_BODY,
    delivery: 'demand',
    reason: 'fixture canon',
  })
})

afterEach(() => {
  installRecordApiClient(null)
  rmSync(root, { recursive: true, force: true })
})

function deps() {
  return {
    environment,
    local: db(),
    runsDirectory: join(root, 'runs'),
    workerProcess: () => false,
    owner: async () => OWNER,
    pull: async () => {
      pulls++
    },
  }
}

function writeCurrentSettings() {
  writeFileSync(
    join(root, '.claude', 'settings.json'),
    `${JSON.stringify(
      {
        ...withMachineBoardHooks({ permissions: { allow: ['Bash(orch *)'] }, hooks: {} }),
        env: {},
      },
      null,
      2,
    )}\n`,
  )
}

describe('settings apply', () => {
  test('--check reports current and changed targets without writing', async () => {
    writeCurrentSettings()
    const before = readFileSync(join(root, '.claude', 'settings.json'), 'utf8')
    const results = await applyMachineSettings({ check: true }, deps())
    expect(pulls).toBe(0)
    expect(results[0]).toMatchObject({ outcome: 'current', changed: false })
    expect(results.slice(1)).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          target: expect.stringContaining('canon claude'),
          detail: 'would apply',
        }),
        expect.objectContaining({
          target: expect.stringContaining('canon codex'),
          detail: 'would apply',
        }),
      ]),
    )
    expect(readFileSync(join(root, '.claude', 'settings.json'), 'utf8')).toBe(before)
    expect(existsSync(join(root, '.claude', 'CLAUDE.md'))).toBe(false)
    expect(existsSync(join(root, '.codex', 'AGENTS.md'))).toBe(false)
  })

  test('applies changed settings with a backup and reports new canon files', async () => {
    writeFileSync(join(root, '.claude', 'settings.json'), '{"permissions":{},"hooks":{}}\n')
    const results = await applyMachineSettings({ check: false }, deps())
    expect(results[0]).toMatchObject({
      outcome: 'applied',
      detail: expect.stringContaining('backup '),
    })
    expect(results.slice(1)).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          target: expect.stringContaining('canon claude'),
          detail: 'created new file',
        }),
        expect.objectContaining({
          target: expect.stringContaining('canon codex'),
          detail: 'created new file',
        }),
      ]),
    )
    expect(readFileSync(join(root, '.claude', 'settings.json'), 'utf8')).toContain('Bash(orch *)')
    expect(readFileSync(join(root, '.codex', 'AGENTS.md'), 'utf8')).toContain('Generated by')
  })

  test('renders hosted settings merged with the machine overlay and reports unmatched drops', async () => {
    const config = join(root, '.config', PLATFORM_SLUG)
    mkdirSync(config, { recursive: true })
    writeFileSync(
      join(config, 'machine.toml'),
      '[permissions]\nallow = ["Bash(git status)"]\n' +
        '[permissions.drop]\nallow = ["Bash(orch *)", "Bash(missing)"]\n',
    )
    writeCurrentSettings()
    const results = await applyMachineSettings({ check: false }, deps())
    expect(results[0]).toMatchObject({
      outcome: 'applied',
      detail: expect.stringContaining('unmatched drop(s): allow Bash(missing)'),
    })
    expect(
      JSON.parse(readFileSync(join(root, '.claude', 'settings.json'), 'utf8')).permissions,
    ).toEqual({ allow: ['Bash(git status)'] })
  })

  test('a canon planning refusal preserves the atomic batch and reports every home', async () => {
    writeCurrentSettings()
    writeFileSync(join(root, '.claude', 'CLAUDE.md'), 'unique local instructions\n')
    const results = await applyMachineSettings({ check: false }, deps())
    expect(results[0]).toMatchObject({ outcome: 'current' })
    expect(results).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          target: expect.stringContaining('canon claude'),
          outcome: 'refused',
          detail: expect.stringContaining('refusing to overwrite unmarked'),
        }),
        expect.objectContaining({
          target: expect.stringContaining('canon codex'),
          outcome: 'refused',
          detail: 'not written: canon batch refused',
        }),
      ]),
    )
    expect(existsSync(join(root, '.codex', 'AGENTS.md'))).toBe(false)
  })

  test('an empty user canon store refuses managed-file deletes in apply and check modes', async () => {
    writeCurrentSettings()
    db().query("DELETE FROM doc WHERE scope='canon' AND owner=?").run(OWNER)
    const claudePath = join(root, '.claude', 'CLAUDE.md')
    const codexPath = join(root, '.codex', 'AGENTS.md')
    writeFileSync(claudePath, `${USER_CANON_MANAGED_MARKER}other store`)
    writeFileSync(codexPath, `${USER_CANON_MANAGED_MARKER}other store`)
    let applies = 0

    for (const check of [false, true]) {
      const results = await applyMachineSettings(
        { check },
        {
          ...deps(),
          applyCanon: () => {
            applies++
            return { backups: [], cleanupFailures: [] }
          },
        },
      )
      expect(results.slice(1)).toEqual(
        expect.arrayContaining([
          expect.objectContaining({
            target: expect.stringContaining('canon claude'),
            outcome: 'refused',
            detail: expect.stringMatching(
              /this store holds no user canon.*orch canon import --user.*remove the files yourself/,
            ),
            changed: false,
          }),
          expect.objectContaining({
            target: expect.stringContaining('canon codex'),
            outcome: 'refused',
            changed: false,
          }),
        ]),
      )
      expect(readFileSync(claudePath, 'utf8')).toBe(`${USER_CANON_MANAGED_MARKER}other store`)
      expect(readFileSync(codexPath, 'utf8')).toBe(`${USER_CANON_MANAGED_MARKER}other store`)
    }
    expect(applies).toBe(0)
  })

  test('a settings changed-after-planning refusal does not stop canon', async () => {
    writeFileSync(join(root, '.claude', 'settings.json'), '{"permissions":{},"hooks":{}}\n')
    const path = join(root, '.claude', 'settings.json')
    const results = await applyMachineSettings(
      { check: false },
      {
        ...deps(),
        applySettings: (plan, state) => {
          writeFileSync(path, '{"permissions":{"ask":[]},"hooks":{}}\n')
          return applySettingsWrite(plan, state)
        },
      },
    )
    expect(results[0]).toMatchObject({
      outcome: 'refused',
      detail: expect.stringContaining('changed after planning'),
    })
    expect(results.slice(1).every((result) => result.outcome === 'applied')).toBe(true)
  })

  test('refuses from an orch worker before pulling or opening writable state', async () => {
    await expect(
      applyMachineSettings(
        { check: true },
        {
          workerProcess: () => true,
          pull: async () => {
            pulls++
          },
        },
      ),
    ).rejects.toThrow('refusing settings apply from an orch worker run')
    expect(pulls).toBe(0)
  })

  test('skips successfully when another settings apply holds the per-user lock', async () => {
    const stateDirectory = join(root, 'state', 'orchestrator')
    mkdirSync(stateDirectory, { recursive: true })
    const lease = tryKernelLease(join(stateDirectory, 'settings-apply.lock'), true)
    expect(lease).not.toBeNull()
    try {
      expect(await applyMachineSettings({ check: false }, deps())).toEqual([
        { target: 'settings apply', outcome: 'skipped', changed: false },
      ])
      expect(pulls).toBe(0)
    } finally {
      lease!.release()
    }
  })

  test('presentation emits exactly one line per target', () => {
    const lines: string[] = []
    printMachineSettingsApplyResults(
      [
        { target: 'settings one', outcome: 'current', changed: false },
        { target: 'canon two', outcome: 'refused', detail: 'first\nsecond', changed: false },
        { target: 'settings apply', outcome: 'skipped', changed: false },
      ],
      (...values) => lines.push(values.join(' ')),
    )
    expect(lines).toEqual([
      'settings one: already current',
      'canon two: refused; first; second',
      'settings apply already running; skipped',
    ])
  })
})
