ALTER TABLE "hub_task" FORCE ROW LEVEL SECURITY;
ALTER TABLE "hub_task_comment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "hub_task_document" FORCE ROW LEVEL SECURITY;
ALTER TABLE "hub_task_status_event" FORCE ROW LEVEL SECURITY;
