// concern: record-sync
/** The payload contracts for every outbox kind registered by record sync. */
import {
  REVIEW_FINDING_RECORD_PAYLOAD_CONTRACT,
  REVIEW_LENS_RECORD_PAYLOAD_CONTRACT,
  REVIEW_READ_RECORD_PAYLOAD_CONTRACT,
  REVIEW_RECORD_PAYLOAD_CONTRACT,
} from '../review/review-outbox.ts'
import { QUESTION_RECORD_PAYLOAD_CONTRACT } from '../run/question-outbox.ts'
import { RUN_RECORD_PAYLOAD_CONTRACT } from '../run/run-outbox.ts'
import { SCORE_RECORD_PAYLOAD_CONTRACT } from '../score/score-outbox.ts'
import {
  CONTENTION_RECORD_PAYLOAD_CONTRACT,
  LANDING_OVERRIDE_RECORD_PAYLOAD_CONTRACT,
  LANDING_RECORD_PAYLOAD_CONTRACT,
  LANDING_REVIEW_CARRY_RECORD_PAYLOAD_CONTRACT,
  LANDING_TRIAGE_SNAPSHOT_RECORD_PAYLOAD_CONTRACT,
  TEST_FLAKE_RECORD_PAYLOAD_CONTRACT,
} from './landing-outbox.ts'

export const OUTBOX_PAYLOAD_CONTRACTS = {
  run: RUN_RECORD_PAYLOAD_CONTRACT,
  score: SCORE_RECORD_PAYLOAD_CONTRACT,
  question: QUESTION_RECORD_PAYLOAD_CONTRACT,
  review: REVIEW_RECORD_PAYLOAD_CONTRACT,
  review_lens: REVIEW_LENS_RECORD_PAYLOAD_CONTRACT,
  review_finding: REVIEW_FINDING_RECORD_PAYLOAD_CONTRACT,
  review_read: REVIEW_READ_RECORD_PAYLOAD_CONTRACT,
  landing: LANDING_RECORD_PAYLOAD_CONTRACT,
  landing_override: LANDING_OVERRIDE_RECORD_PAYLOAD_CONTRACT,
  landing_review_carry: LANDING_REVIEW_CARRY_RECORD_PAYLOAD_CONTRACT,
  landing_triage_snapshot: LANDING_TRIAGE_SNAPSHOT_RECORD_PAYLOAD_CONTRACT,
  contention: CONTENTION_RECORD_PAYLOAD_CONTRACT,
  test_flake: TEST_FLAKE_RECORD_PAYLOAD_CONTRACT,
} as const
