/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DoneRouteImport } from './routes/done'
import { Route as FlightRouteImport } from './routes/flight'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RatioRouteImport } from './routes/ratio'
import { Route as RoutingRouteImport } from './routes/routing'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpendRouteImport } from './routes/spend'
import { Route as ProjectsNameRouteImport } from './routes/projects.$name'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as BoardTasksKeyRouteImport } from './routes/board.tasks.$key'
import { Route as DoneTasksKeyRouteImport } from './routes/done.tasks.$key'
import { Route as FlightTasksKeyRouteImport } from './routes/flight.tasks.$key'
import { Route as DocsScopeSubjectSlugRouteImport } from './routes/docs.$scope.$subject.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightRoute = FlightRouteImport.update({
  id: '/flight',
  path: '/flight',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RatioRoute = RatioRouteImport.update({
  id: '/ratio',
  path: '/ratio',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendRoute = SpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNameRoute = ProjectsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ProjectsRoute,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RunsRoute,
} as any)
const BoardTasksKeyRoute = BoardTasksKeyRouteImport.update({
  id: '/tasks/$key',
  path: '/tasks/$key',
  getParentRoute: () => BoardRoute,
} as any)
const DoneTasksKeyRoute = DoneTasksKeyRouteImport.update({
  id: '/tasks/$key',
  path: '/tasks/$key',
  getParentRoute: () => DoneRoute,
} as any)
const FlightTasksKeyRoute = FlightTasksKeyRouteImport.update({
  id: '/tasks/$key',
  path: '/tasks/$key',
  getParentRoute: () => FlightRoute,
} as any)
const DocsScopeSubjectSlugRoute = DocsScopeSubjectSlugRouteImport.update({
  id: '/$scope/$subject/$slug',
  path: '/$scope/$subject/$slug',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/board': typeof BoardRouteWithChildren
  '/design': typeof DesignRoute
  '/docs': typeof DocsRouteWithChildren
  '/done': typeof DoneRouteWithChildren
  '/flight': typeof FlightRouteWithChildren
  '/jobs': typeof JobsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/ratio': typeof RatioRoute
  '/routing': typeof RoutingRoute
  '/runs': typeof RunsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spend': typeof SpendRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/runs/$id': typeof RunsIdRoute
  '/board/tasks/$key': typeof BoardTasksKeyRoute
  '/done/tasks/$key': typeof DoneTasksKeyRoute
  '/flight/tasks/$key': typeof FlightTasksKeyRoute
  '/docs/$scope/$subject/$slug': typeof DocsScopeSubjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/board': typeof BoardRouteWithChildren
  '/design': typeof DesignRoute
  '/docs': typeof DocsRouteWithChildren
  '/done': typeof DoneRouteWithChildren
  '/flight': typeof FlightRouteWithChildren
  '/jobs': typeof JobsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/ratio': typeof RatioRoute
  '/routing': typeof RoutingRoute
  '/runs': typeof RunsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spend': typeof SpendRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/runs/$id': typeof RunsIdRoute
  '/board/tasks/$key': typeof BoardTasksKeyRoute
  '/done/tasks/$key': typeof DoneTasksKeyRoute
  '/flight/tasks/$key': typeof FlightTasksKeyRoute
  '/docs/$scope/$subject/$slug': typeof DocsScopeSubjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/board': typeof BoardRouteWithChildren
  '/design': typeof DesignRoute
  '/docs': typeof DocsRouteWithChildren
  '/done': typeof DoneRouteWithChildren
  '/flight': typeof FlightRouteWithChildren
  '/jobs': typeof JobsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/ratio': typeof RatioRoute
  '/routing': typeof RoutingRoute
  '/runs': typeof RunsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spend': typeof SpendRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/runs/$id': typeof RunsIdRoute
  '/board/tasks/$key': typeof BoardTasksKeyRoute
  '/done/tasks/$key': typeof DoneTasksKeyRoute
  '/flight/tasks/$key': typeof FlightTasksKeyRoute
  '/docs/$scope/$subject/$slug': typeof DocsScopeSubjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/board'
    | '/design'
    | '/docs'
    | '/done'
    | '/flight'
    | '/jobs'
    | '/projects'
    | '/ratio'
    | '/routing'
    | '/runs'
    | '/settings'
    | '/spend'
    | '/projects/$name'
    | '/runs/$id'
    | '/board/tasks/$key'
    | '/done/tasks/$key'
    | '/flight/tasks/$key'
    | '/docs/$scope/$subject/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/board'
    | '/design'
    | '/docs'
    | '/done'
    | '/flight'
    | '/jobs'
    | '/projects'
    | '/ratio'
    | '/routing'
    | '/runs'
    | '/settings'
    | '/spend'
    | '/projects/$name'
    | '/runs/$id'
    | '/board/tasks/$key'
    | '/done/tasks/$key'
    | '/flight/tasks/$key'
    | '/docs/$scope/$subject/$slug'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/board'
    | '/design'
    | '/docs'
    | '/done'
    | '/flight'
    | '/jobs'
    | '/projects'
    | '/ratio'
    | '/routing'
    | '/runs'
    | '/settings'
    | '/spend'
    | '/projects/$name'
    | '/runs/$id'
    | '/board/tasks/$key'
    | '/done/tasks/$key'
    | '/flight/tasks/$key'
    | '/docs/$scope/$subject/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  BoardRoute: typeof BoardRouteWithChildren
  DesignRoute: typeof DesignRoute
  DocsRoute: typeof DocsRouteWithChildren
  DoneRoute: typeof DoneRouteWithChildren
  FlightRoute: typeof FlightRouteWithChildren
  JobsRoute: typeof JobsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RatioRoute: typeof RatioRoute
  RoutingRoute: typeof RoutingRoute
  RunsRoute: typeof RunsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SpendRoute: typeof SpendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight': {
      id: '/flight'
      path: '/flight'
      fullPath: '/flight'
      preLoaderRoute: typeof FlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratio': {
      id: '/ratio'
      path: '/ratio'
      fullPath: '/ratio'
      preLoaderRoute: typeof RatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spend': {
      id: '/spend'
      path: '/spend'
      fullPath: '/spend'
      preLoaderRoute: typeof SpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$name': {
      id: '/projects/$name'
      path: '/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof ProjectsNameRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof RunsRoute
    }
    '/board/tasks/$key': {
      id: '/board/tasks/$key'
      path: '/tasks/$key'
      fullPath: '/board/tasks/$key'
      preLoaderRoute: typeof BoardTasksKeyRouteImport
      parentRoute: typeof BoardRoute
    }
    '/done/tasks/$key': {
      id: '/done/tasks/$key'
      path: '/tasks/$key'
      fullPath: '/done/tasks/$key'
      preLoaderRoute: typeof DoneTasksKeyRouteImport
      parentRoute: typeof DoneRoute
    }
    '/flight/tasks/$key': {
      id: '/flight/tasks/$key'
      path: '/tasks/$key'
      fullPath: '/flight/tasks/$key'
      preLoaderRoute: typeof FlightTasksKeyRouteImport
      parentRoute: typeof FlightRoute
    }
    '/docs/$scope/$subject/$slug': {
      id: '/docs/$scope/$subject/$slug'
      path: '/$scope/$subject/$slug'
      fullPath: '/docs/$scope/$subject/$slug'
      preLoaderRoute: typeof DocsScopeSubjectSlugRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface BoardRouteChildren {
  BoardTasksKeyRoute: typeof BoardTasksKeyRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardTasksKeyRoute: BoardTasksKeyRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

interface DocsRouteChildren {
  DocsScopeSubjectSlugRoute: typeof DocsScopeSubjectSlugRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsScopeSubjectSlugRoute: DocsScopeSubjectSlugRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface DoneRouteChildren {
  DoneTasksKeyRoute: typeof DoneTasksKeyRoute
}

const DoneRouteChildren: DoneRouteChildren = {
  DoneTasksKeyRoute: DoneTasksKeyRoute,
}

const DoneRouteWithChildren = DoneRoute._addFileChildren(DoneRouteChildren)

interface FlightRouteChildren {
  FlightTasksKeyRoute: typeof FlightTasksKeyRoute
}

const FlightRouteChildren: FlightRouteChildren = {
  FlightTasksKeyRoute: FlightTasksKeyRoute,
}

const FlightRouteWithChildren =
  FlightRoute._addFileChildren(FlightRouteChildren)

interface ProjectsRouteChildren {
  ProjectsNameRoute: typeof ProjectsNameRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsNameRoute: ProjectsNameRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface RunsRouteChildren {
  RunsIdRoute: typeof RunsIdRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsIdRoute: RunsIdRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  BoardRoute: BoardRouteWithChildren,
  DesignRoute: DesignRoute,
  DocsRoute: DocsRouteWithChildren,
  DoneRoute: DoneRouteWithChildren,
  FlightRoute: FlightRouteWithChildren,
  JobsRoute: JobsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RatioRoute: RatioRoute,
  RoutingRoute: RoutingRoute,
  RunsRoute: RunsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SpendRoute: SpendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
