ALTER TABLE "config_entry" FORCE ROW LEVEL SECURITY;
ALTER TABLE "config_secret" FORCE ROW LEVEL SECURITY;
ALTER TABLE "secret_dek" FORCE ROW LEVEL SECURITY;
ALTER TABLE "secret_dek_wrap" FORCE ROW LEVEL SECURITY;
ALTER TABLE "machine_public_key" FORCE ROW LEVEL SECURITY;
