// concern: codex-project-doc
/** Composes Codex's generated project document from repository canon rows. */
import { CODEX_PROJECT_DOC_MAX_BYTES } from './canon-load.ts'

export const CODEX_PROJECT_DOC_PATH = 'AGENTS.override.md'
export const CODEX_PROJECT_DOC_HEADER =
  '<!-- Generated by `orch canon hydrate`; do not edit. Edit canon with `orch doc set --scope canon`. -->'

type CanonRow = { slug: string; body: string }

export type CodexProjectDoc = {
  body: string
  bytes: number
  contributors: Array<{ slug: string; bytes: number }>
}

/** The root entry precedes always-on rules in the same path order used by hydration. */
export function composeCodexProjectDoc(rows: CanonRow[]): CodexProjectDoc | null {
  const entry = rows.find(({ slug }) => slug === 'AGENTS.md')
  if (!entry) return null
  const sources = [
    entry,
    ...rows
      .filter(({ slug }) => /^\.agents\/rules\/[^/]+\.md$/.test(slug))
      .sort((left, right) => left.slug.localeCompare(right.slug)),
  ]
  const body = `${[CODEX_PROJECT_DOC_HEADER, ...sources.map((row) => row.body.trimEnd())].join('\n\n')}\n`
  return {
    body,
    bytes: Buffer.byteLength(body, 'utf8'),
    contributors: sources
      .map(({ slug, body: sourceBody }) => ({
        slug,
        bytes: Buffer.byteLength(sourceBody.trimEnd(), 'utf8'),
      }))
      .sort((left, right) => right.bytes - left.bytes || left.slug.localeCompare(right.slug)),
  }
}

export function codexProjectDocBudgetRefusal(doc: CodexProjectDoc): string | null {
  if (doc.bytes <= CODEX_PROJECT_DOC_MAX_BYTES) return null
  const largest = doc.contributors
    .slice(0, 3)
    .map(({ slug, bytes }) => `${slug} (${bytes} bytes)`)
    .join(', ')
  return (
    `refusing canon hydrate: ${CODEX_PROJECT_DOC_PATH} measures ${doc.bytes} bytes; ` +
    `limit ${CODEX_PROJECT_DOC_MAX_BYTES} bytes; largest contributing rows: ${largest}`
  )
}
