// concern: user-canon-home
/** Pure Claude-home mapping and hydration decisions. Must not know filesystems, stores, commands, or transports. */
import { posix } from 'node:path'
import { PLATFORM_NAME } from '../../../shared/brand.ts'

export const USER_CANON_MANAGED_MARKER = `<!-- Generated by ${PLATFORM_NAME}; edit with: orch doc set --scope canon --user -->\n`

export const USER_CANON_HOME_MAPPINGS = [
  {
    harness: 'claude',
    environment: null,
    defaultDirectory: '.claude',
    entry: { canon: 'AGENTS.md', home: 'CLAUDE.md' },
    rules: { canonPrefix: '.agents/rules/', homeDirectory: 'rules' },
  },
  {
    harness: 'codex',
    environment: 'CODEX_HOME',
    defaultDirectory: '.codex',
    entry: { canon: 'AGENTS.md', home: 'AGENTS.md' },
    rules: null,
  },
  {
    harness: 'grok',
    environment: 'GROK_HOME',
    defaultDirectory: '.grok',
    entry: { canon: 'AGENTS.md', home: 'AGENTS.md' },
    rules: null,
  },
] as const

export type UserCanonHomeMapping = (typeof USER_CANON_HOME_MAPPINGS)[number]

export type UserCanonPath = { kind: 'canon'; path: string } | { kind: 'claude'; path: string }

/** Maps one supported user-canon path to its counterpart in the Claude home. */
export function mapUserCanonPath(input: UserCanonPath): string | null {
  const mapping = USER_CANON_HOME_MAPPINGS[0]
  if (input.kind === 'canon') {
    if (input.path === mapping.entry.canon) return mapping.entry.home
    const match = /^\.agents\/rules\/([^/]+\.md)$/.exec(input.path)
    return match ? posix.join(mapping.rules.homeDirectory, match[1]!) : null
  }
  if (input.path === mapping.entry.home) return mapping.entry.canon
  const match = /^rules\/([^/]+\.md)$/.exec(input.path)
  return match ? posix.join(mapping.rules.canonPrefix, match[1]!) : null
}

export function mapUserCanonHomePath(mapping: UserCanonHomeMapping, slug: string): string | null {
  if (slug === mapping.entry.canon) return mapping.entry.home
  if (!mapping.rules || !slug.startsWith(mapping.rules.canonPrefix)) return null
  const name = slug.slice(mapping.rules.canonPrefix.length)
  return /^[^/]+\.md$/.test(name) ? posix.join(mapping.rules.homeDirectory, name) : null
}

export function isUserCanonSlug(slug: string): boolean {
  return mapUserCanonPath({ kind: 'canon', path: slug }) !== null
}

export function userCanonHomeImportDeletionSlugs(
  currentSlugs: string[],
  importedSlugs: Iterable<string>,
): string[] {
  const imported = new Set(importedSlugs)
  return currentSlugs.filter((slug) => isUserCanonSlug(slug) && !imported.has(slug))
}

export function stripUserCanonManagedMarker(text: string): string {
  return text.startsWith(USER_CANON_MANAGED_MARKER)
    ? text.slice(USER_CANON_MANAGED_MARKER.length)
    : text
}

export type UserCanonHydrationDecision =
  | { action: 'write'; body: string }
  | { action: 'delete' }
  | { action: 'leave' }
  | { action: 'refuse' }

/** Protects an unmarked home file as the possible only copy of personal rules. */
export function decideUserCanonHydration(input: {
  storeBody: string | null
  homeText: string | null
}): UserCanonHydrationDecision {
  const marked = input.homeText?.startsWith(USER_CANON_MANAGED_MARKER) ?? false
  if (input.storeBody === null) return marked ? { action: 'delete' } : { action: 'leave' }

  const desired = `${USER_CANON_MANAGED_MARKER}${input.storeBody}`
  if (input.homeText === desired) return { action: 'leave' }
  if (input.homeText === null || marked || input.homeText === input.storeBody) {
    return { action: 'write', body: desired }
  }
  return { action: 'refuse' }
}
