// concern: user-canon-home
/** Pure Claude-home mapping and hydration decisions. Must not know filesystems, stores, commands, or transports. */
import { posix } from 'node:path'
import { PLATFORM_NAME } from '../../../shared/brand.ts'

export const USER_CANON_MANAGED_MARKER = `<!-- Generated by ${PLATFORM_NAME}; edit with: orch doc set --scope canon --user -->\n`

export type UserCanonPath = { kind: 'canon'; path: string } | { kind: 'claude'; path: string }

/** Maps one supported user-canon path to its counterpart in the Claude home. */
export function mapUserCanonPath(input: UserCanonPath): string | null {
  if (input.kind === 'canon') {
    if (input.path === 'AGENTS.md') return 'CLAUDE.md'
    const match = /^\.agents\/rules\/([^/]+\.md)$/.exec(input.path)
    return match ? posix.join('rules', match[1]!) : null
  }
  if (input.path === 'CLAUDE.md') return 'AGENTS.md'
  const match = /^rules\/([^/]+\.md)$/.exec(input.path)
  return match ? posix.join('.agents/rules', match[1]!) : null
}

export function stripUserCanonManagedMarker(text: string): string {
  return text.startsWith(USER_CANON_MANAGED_MARKER)
    ? text.slice(USER_CANON_MANAGED_MARKER.length)
    : text
}

export type UserCanonHydrationDecision =
  | { action: 'write'; body: string }
  | { action: 'delete' }
  | { action: 'leave' }
  | { action: 'refuse' }

/** Protects an unmarked home file as the possible only copy of personal rules. */
export function decideUserCanonHydration(input: {
  storeBody: string | null
  homeText: string | null
}): UserCanonHydrationDecision {
  const marked = input.homeText?.startsWith(USER_CANON_MANAGED_MARKER) ?? false
  if (input.storeBody === null) return marked ? { action: 'delete' } : { action: 'leave' }

  const desired = `${USER_CANON_MANAGED_MARKER}${input.storeBody}`
  if (input.homeText === desired) return { action: 'leave' }
  if (input.homeText === null || marked || input.homeText === input.storeBody) {
    return { action: 'write', body: desired }
  }
  return { action: 'refuse' }
}
