import { dirname, normalize } from 'node:path'
import type { ImportBoundary } from './architecture-boundaries.ts'

const boundary = (
  name: string,
  file: string,
  allowed: string[],
  reason: string,
  typeOnlyAllowed: string[] = [],
): ImportBoundary => ({
  name,
  file,
  allowed: allowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
  typeOnlyAllowed: typeOnlyAllowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
  reason,
})

export const recordReadBoundariesBeforePublish: ImportBoundary[] = [
  boundary(
    'record-doc-api-schemas-boundary',
    'orchestrator/src/record/record-api-doc-schemas.ts',
    ['zod', '../../../shared/docs.ts', '../canon/user-canon-home.ts'],
    'Keep hosted document payload validation independent of SQL and local execution.',
  ),
  boundary(
    'record-auth-boundary',
    'orchestrator/src/record/record-auth.ts',
    [
      '@better-auth/drizzle-adapter/relations-v2',
      'better-auth',
      'better-auth/plugins',
      'bun',
      'drizzle-orm/bun-sql',
      '../../../shared/record/schema.ts',
      '../../../shared/record-remedies.ts',
      '../../../shared/record/schema-auth.ts',
      '../mail/invitation-mailer.ts',
      '../mail/password-reset-mailer.ts',
      './record-invitation.ts',
    ],
    'Enforce the record-auth concern boundary.',
  ),
  boundary(
    'record-config-boundary',
    'orchestrator/src/record/record-config.ts',
    [
      'bun',
      '../../../shared/machine-key-id.ts',
      '../../../shared/record/schema.ts',
      '../../../shared/record/tenant.ts',
    ],
    'Enforce the hosted config service concern boundary.',
  ),
  boundary(
    'record-docs-boundary',
    'orchestrator/src/record/record-docs.ts',
    [
      'bun',
      '../../../shared/docs.ts',
      '../../../shared/record/schema.ts',
      '../../../shared/record/tenant.ts',
      '../canon/canon-import-policy.ts',
      '../doc/doc-write-allowed.ts',
      './record-canon-facts.ts',
      './record-doc-errors.ts',
      './record-doc-mapping.ts',
      './record-doc-tree.ts',
    ],
    'Enforce the record-docs concern boundary.',
    ['../canon/canon-lint.ts'],
  ),
  boundary(
    'record-doc-tree-boundary',
    'orchestrator/src/record/record-doc-tree.ts',
    ['bun', '../doc/doc-tree-rules.ts'],
    'Keep hosted document tree fact gathering limited to SQL and the pure tree decision.',
    ['../../../shared/docs.ts'],
  ),
  boundary(
    'record-doc-mapping-boundary',
    'orchestrator/src/record/record-doc-mapping.ts',
    [],
    'Keep hosted document row mapping independent of SQL and transports.',
    ['../../../shared/docs.ts', '../doc/doc-write-allowed.ts'],
  ),
]

export const recordReadBoundariesAfterPublish: ImportBoundary[] = [
  boundary(
    'verdict-payload-boundary',
    'orchestrator/src/verdict/verdict-payload.ts',
    ['zod', '../review/review-vocabulary.ts', '../score/score.ts'],
    'Keep the verdict transport contract independent of persistence and delivery adapters.',
  ),
  boundary(
    'verdict-rules-boundary',
    'orchestrator/src/verdict/verdict-rules.ts',
    ['../failure/failure.ts', '../score/score.ts'],
    'Keep verdict policy pure and independent of local and hosted persistence adapters.',
  ),
  boundary(
    'record-verdicts-boundary',
    'orchestrator/src/record/record-verdicts.ts',
    ['bun', '../score/score.ts', '../verdict/verdict-payload.ts', '../verdict/verdict-rules.ts'],
    'Enforce the record-verdicts concern boundary.',
  ),
  boundary(
    'record-projects-boundary',
    'orchestrator/src/record/record-projects.ts',
    [
      'bun',
      '../../../shared/record/schema.ts',
      '../../../shared/record/tenant.ts',
      './record-project-columns.ts',
      './record-project-write.ts',
    ],
    'Keep hosted project record access isolated from other production modules.',
  ),
  boundary(
    'record-reviews-boundary',
    'orchestrator/src/record/record-reviews.ts',
    ['bun', '../../../shared/record/tenant.ts', './record-runs.ts'],
    'Keep hosted review record access limited to the hosted run record contract.',
  ),
  boundary(
    'record-runs-window-query-boundary',
    'orchestrator/src/record/record-runs-window-query.ts',
    ['zod'],
    'Keep the hosted run window query contract free of how the window is read.',
  ),
  boundary(
    'record-runs-boundary',
    'orchestrator/src/record/record-runs.ts',
    [
      'bun',
      '../../../shared/record/tenant.ts',
      '../failure/failure.ts',
      '../hook-tree/hook-tree.ts',
    ],
    'Enforce the record-runs concern boundary; the window counters share the local definitions of evidence and the hook-tree job.',
  ),
  boundary(
    'record-snapshots-boundary',
    'orchestrator/src/record/record-snapshots.ts',
    ['bun', '../../../shared/record/schema.ts', '../../../shared/record/tenant.ts'],
    'Enforce the hosted snapshot service concern boundary.',
  ),
  boundary(
    'record-board-contract-boundary',
    'orchestrator/src/record/record-board-contract.ts',
    [],
    'Keep the hosted board JSON contract free of SQL and local stores.',
  ),
  boundary(
    'record-board-scope-boundary',
    'orchestrator/src/record/record-board-scope.ts',
    ['../board/board-policy.ts', '../board/board-tags.ts', './record-board-contract.ts'],
    'Keep hosted board scope and create-content decisions pure.',
  ),
  boundary(
    'record-board-tx-boundary',
    'orchestrator/src/record/record-board-tx.ts',
    ['bun', '../../../shared/record/tenant.ts', './record-board-contract.ts'],
    'Keep hosted board transactions independent of HTTP and local stores.',
  ),
  boundary(
    'record-board-messages-boundary',
    'orchestrator/src/record/record-board-messages.ts',
    [
      'bun',
      '../../../shared/secret-shaped.ts',
      '../board/board-policy.ts',
      '../board/board-tags.ts',
      '../board/board-thread-policy.ts',
      './record-board-contract.ts',
      './record-board-scope.ts',
      './record-board-tx.ts',
    ],
    'Keep hosted board message services independent of HTTP and local stores.',
  ),
  boundary(
    'record-board-receipts-boundary',
    'orchestrator/src/record/record-board-receipts.ts',
    ['./record-board-contract.ts', './record-board-messages.ts', './record-board-tx.ts'],
    'Keep hosted board receipts independent of HTTP and local stores.',
  ),
  boundary(
    'record-board-changes-boundary',
    'orchestrator/src/record/record-board-changes.ts',
    [
      '../board/board-tags.ts',
      './record-board-contract.ts',
      './record-board-messages.ts',
      './record-board-receipts.ts',
      './record-board-tx.ts',
    ],
    'Keep the hosted board change cursor independent of HTTP and local stores.',
  ),
  boundary(
    'record-board-overview-boundary',
    'orchestrator/src/record/record-board-overview.ts',
    [
      'bun',
      '../board/board-tags.ts',
      './record-board-contract.ts',
      './record-board-messages.ts',
      './record-board-receipts.ts',
      './record-board-tx.ts',
    ],
    'Keep the hosted board overview independent of HTTP and local stores.',
  ),
  boundary(
    'record-board-claims-boundary',
    'orchestrator/src/record/record-board-claims.ts',
    [
      'bun',
      '../../../shared/record/schema.ts',
      '../board/board-claim-policy.ts',
      '../board/board-policy.ts',
      './record-board-contract.ts',
      './record-board-messages.ts',
      './record-board-scope.ts',
      './record-board-tx.ts',
    ],
    'Keep hosted board claims independent of HTTP and local stores.',
  ),
  boundary(
    'record-api-board-boundary',
    'orchestrator/src/record/record-api-board.ts',
    ['hono', 'zod', './record-auth.ts', './record-board-contract.ts', './record-board-tx.ts'],
    'Keep hosted board routes independent of SQL and local execution.',
  ),
]

export const recordSchemaBoundaries: ImportBoundary[] = [
  boundary(
    'record-project-columns-boundary',
    'orchestrator/src/record/record-project-columns.ts',
    [],
    'Keep the hosted project column mapping pure and independent of SQL, HTTP, and stores.',
    ['../project/project-settings.ts'],
  ),
  boundary(
    'project-settings-boundary',
    'orchestrator/src/project/project-settings.ts',
    [],
    'Keep the project settings shape independent of stores, SQL, and HTTP.',
    [
      '../../../shared/trackers.ts',
      '../recipe/recipe.ts',
      '../workflow/autonomy.ts',
      '../worktree/worktree-provision.ts',
      '../worktree/worktree-template.ts',
      './project-injection.ts',
    ],
  ),
  boundary(
    'postgres-schema-config-boundary',
    'shared/record/schema-config.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted config schema concern boundary.',
  ),
  boundary(
    'postgres-schema-auth-boundary',
    'shared/record/schema-auth.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', './schema.ts'],
    'Enforce the Better Auth schema concern boundary.',
  ),
  boundary(
    'postgres-schema-docs-boundary',
    'shared/record/schema-docs.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', '../docs.ts', './schema.ts'],
    'Enforce the hosted doc schema concern boundary.',
  ),
  boundary(
    'postgres-schema-hub-boundary',
    'shared/record/schema-hub.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted hub evidence schema concern boundary.',
  ),
  boundary(
    'postgres-schema-landing-boundary',
    'shared/record/schema-landing.ts',
    ['drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted landing schema concern boundary.',
  ),
  boundary(
    'postgres-schema-review-boundary',
    'shared/record/schema-review.ts',
    ['drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted review schema concern boundary.',
  ),
  boundary(
    'postgres-schema-run-boundary',
    'shared/record/schema-run.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted run schema concern boundary.',
  ),
  boundary(
    'postgres-schema-question-boundary',
    'shared/record/schema-question.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', './schema.ts', './schema-run.ts'],
    'Enforce the hosted question schema concern boundary.',
  ),
  boundary(
    'postgres-schema-snapshots-boundary',
    'shared/record/schema-snapshots.ts',
    ['drizzle-orm', 'drizzle-orm/pg-core', './schema.ts'],
    'Enforce the hosted orchestrator snapshot schema concern boundary.',
  ),
]
