export const cleanupBoundarySpecs = [
  {
    name: 'cleanup-sweep-boundary',
    file: 'orchestrator/src/cleanup/cleanup-sweep.ts',
    allowed: [
      'node:fs',
      'node:path',
      './cleanup.ts',
      './cleanup-sweep-decisions.ts',
      './cleanup-sweep-reclaim.ts',
      './cleanup-sweep-residue.ts',
      './reader-clone-archive-retention.ts',
      './cleanup-sweep-docker.ts',
      './claim-reconciliation.ts',
      '../close/close-out.ts',
      '../database/db.ts',
      '../evidence/unjudged-expiry.ts',
      '../resources/docker-resources.ts',
      '../hook-tree/hook-tree.ts',
      '../landing-tree/release-observation.ts',
      '../../../shared/process-identity.ts',
      '../project/projects.ts',
      '../resources/resource-ownership.ts',
      '../resources/main-stack.ts',
      '../run/run-alive.ts',
      '../run/run-artifacts.ts',
      '../run/run-authority.ts',
      '../run/run-lease.ts',
      '../run/synthetic-lifecycle-job.ts',
      '../sandbox/grok-trust.ts',
      '../worktree/worktree-attribution.ts',
      '../worktree/worktree-remove.ts',
      '../worktree/worktree-types.ts',
    ],
    typeOnlyAllowed: [],
    reason:
      'Keep cleanup-sweep independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  },
] as const
