// concern: architecture-manifest
/** Board module allowlists, kept beside the root manifest so it stays within its file ceiling. */
import { dirname, normalize } from 'node:path'

type BoardModule = { file: string; allowed: string[] }

const module = (file: string, allowed: string[]): BoardModule => ({
  file,
  allowed: allowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
})

export const boardModules: BoardModule[] = [
  module('orchestrator/src/board/board-adoption.ts', [
    'bun:sqlite',
    '../../../shared/record/schema.ts',
    '../database/db.ts',
    '../record/machine-identity.ts',
    '../record/record-api-client.ts',
    './board-adoption-policy.ts',
    './board-claim-policy.ts',
    './board-mode.ts',
    './board-policy.ts',
    './board-store.ts',
  ]),
  module('orchestrator/src/board/board-adoption-policy.ts', []),
  module('orchestrator/src/board/board-mode.ts', [
    'bun:sqlite',
    '../../../shared/board-mode.ts',
    '../database/db.ts',
  ]),
  module('orchestrator/src/board/board-hosted-cache.ts', [
    'bun:sqlite',
    '../database/db.ts',
    '../record/record-api-client.ts',
    '../record/record-board-contract.ts',
    './board-mode.ts',
    './board-policy.ts',
    './board-render.ts',
    './board-store.ts',
    './board-tags.ts',
    './board-thread-render.ts',
  ]),
  module('orchestrator/src/board/board-delivery.ts', [
    '../../../shared/board-mode.ts',
    './board-hosted-cache.ts',
    './board-policy.ts',
    './board-service.ts',
  ]),
  module('orchestrator/src/board/board-overview.ts', [
    '../database/db.ts',
    '../record/record-api-client.ts',
    '../record/record-board-contract.ts',
    './board-delivery.ts',
    './board-hosted-cache.ts',
    './board-operations.ts',
    './board-store.ts',
    './board-thread-policy.ts',
  ]),
  module('orchestrator/src/board/board-operations.ts', [
    '../../../shared/record/schema.ts',
    '../database/db.ts',
    '../project/projects.ts',
    '../record/machine-identity.ts',
    '../record/record-api-client.ts',
    '../record/record-board-contract.ts',
    './board-answer-note.ts',
    './board-hosted-cache.ts',
    './board-claim-policy.ts',
    './board-claim-service.ts',
    './board-mode.ts',
    './board-policy.ts',
    './board-service.ts',
    './board-store.ts',
    './board-thread-policy.ts',
    './board-thread-service.ts',
  ]),
  module('orchestrator/src/board/board-claim-policy.ts', [
    '../../../shared/secret-shaped.ts',
    './board-policy.ts',
    './board-tags.ts',
  ]),
  module('orchestrator/src/board/board-policy.ts', ['../../../shared/secret-shaped.ts']),
  module('orchestrator/src/board/board-tags.ts', ['node:path']),
  module('orchestrator/src/board/board-routing.ts', ['./board-tags.ts']),
  module('orchestrator/src/board/board-context.ts', [
    'bun:sqlite',
    '../database/db.ts',
    './board-routing.ts',
  ]),
  module('orchestrator/src/board/board-render.ts', ['./board-policy.ts', './board-tags.ts']),
  module('orchestrator/src/board/board-thread-policy.ts', ['./board-policy.ts']),
  module('orchestrator/src/board/board-thread-render.ts', [
    './board-policy.ts',
    './board-render.ts',
  ]),
  module('orchestrator/src/board/board-answer-note.ts', ['../mcp/hub-notes.ts']),
  module('orchestrator/src/board/board-store.ts', [
    'node:os',
    '../database/db.ts',
    '../project/projects.ts',
    './board-claim-policy.ts',
    './board-context.ts',
    './board-policy.ts',
    './board-render.ts',
    './board-routing.ts',
    './board-tags.ts',
  ]),
  module('orchestrator/src/board/board-service.ts', [
    'node:os',
    '../database/db.ts',
    '../project/projects.ts',
    './board-hosted-cache.ts',
    './board-policy.ts',
    './board-render.ts',
    './board-store.ts',
    './board-thread-render.ts',
  ]),
  module('orchestrator/src/board/board-claim-service.ts', [
    '../database/db.ts',
    '../project/projects.ts',
    './board-claim-policy.ts',
    './board-service.ts',
    './board-store.ts',
  ]),
  module('orchestrator/src/board/board-claim-commands.ts', ['commander', './board-operations.ts']),
  module('orchestrator/src/board/board-thread-service.ts', [
    '../../../shared/secret-shaped.ts',
    '../database/db.ts',
    '../project/projects.ts',
    './board-answer-note.ts',
    './board-policy.ts',
    './board-store.ts',
    './board-thread-policy.ts',
  ]),
  module('orchestrator/src/board/board-suggestions.ts', [
    '../../../shared/secret-shaped.ts',
    '../database/db.ts',
    './board-policy.ts',
    './board-service.ts',
    './board-tags.ts',
  ]),
  module('orchestrator/src/board/board-commands.ts', [
    'commander',
    './board-adoption.ts',
    './board-claim-commands.ts',
    './board-operations.ts',
    './board-overview.ts',
    './board-delivery.ts',
    './board-service.ts',
    './board-suggestions.ts',
  ]),
  module('orchestrator/src/ask/ask-board-tools.ts', [
    '@modelcontextprotocol/server',
    'zod',
    '../board/board-policy.ts',
    '../board/board-suggestions.ts',
  ]),
  module('orchestrator/src/run/run-board-prompt.ts', [
    'node:fs',
    '../board/board-delivery.ts',
    '../database/db.ts',
    './run-process.ts',
  ]),
]
