import type { ImportBoundary } from './architecture-boundaries.ts'

const source = 'orchestrator/src/settings/'

export const settingsBoundarySpecs: ImportBoundary[] = [
  {
    name: 'settings-boundary',
    file: `${source}settings.ts`,
    allowed: ['zod', 'shared/secret-shaped.ts'],
    typeOnlyAllowed: [],
    reason: 'Keep owned settings schema and extraction pure.',
  },
  {
    name: 'settings-render-boundary',
    file: `${source}settings-render.ts`,
    allowed: ['node:crypto', `${source}settings.ts`],
    typeOnlyAllowed: [],
    reason: 'Keep settings file render and drift pure.',
  },
  {
    name: 'settings-lint-boundary',
    file: `${source}settings-lint.ts`,
    allowed: ['shared/ratchet.ts', `${source}settings.ts`],
    typeOnlyAllowed: [],
    reason: 'Keep settings lint decisions pure.',
  },
  {
    name: 'settings-files-boundary',
    file: `${source}settings-files.ts`,
    allowed: ['node:fs', 'node:path', `${source}settings.ts`, `${source}settings-render.ts`],
    typeOnlyAllowed: [],
    reason: 'Keep settings file access independent of stores, commands, and transports.',
  },
  {
    name: 'settings-env-boundary',
    file: `${source}settings-env.ts`,
    allowed: ['node:fs', 'node:path', `${source}settings.ts`],
    typeOnlyAllowed: [],
    reason: 'Keep settings secrets-file access independent of stores and commands.',
  },
  {
    name: 'settings-write-boundary',
    file: `${source}settings-write.ts`,
    allowed: ['node:crypto', 'node:fs', 'node:path', 'shared/state-directory.ts'],
    typeOnlyAllowed: [],
    reason: 'Keep guarded settings writes independent of stores and commands.',
  },
  {
    name: 'settings-apply-commands-boundary',
    file: `${source}settings-apply-commands.ts`,
    allowed: [
      'node:fs',
      'shared/git.ts',
      'shared/machine-config.ts',
      'orchestrator/src/doc/docs.ts',
      'orchestrator/src/project/projects.ts',
      `${source}settings.ts`,
      `${source}settings-env.ts`,
      `${source}settings-files.ts`,
      `${source}settings-render.ts`,
      `${source}settings-permission-overlay.ts`,
      `${source}settings-write.ts`,
    ],
    typeOnlyAllowed: [],
    reason:
      'Keep settings mutation commands independent of runs, routing, transports, and the CLI.',
  },
  {
    name: 'settings-commands-boundary',
    file: `${source}settings-commands.ts`,
    allowed: [
      'shared/ratchet.ts',
      'shared/settings-summary.ts',
      'shared/machine-config.ts',
      'orchestrator/src/doc/doc-write-allowed.ts',
      'orchestrator/src/doc/docs.ts',
      'orchestrator/src/project/projects.ts',
      `${source}settings.ts`,
      `${source}settings-env.ts`,
      `${source}settings-files.ts`,
      `${source}settings-lint.ts`,
      `${source}settings-permission.ts`,
      `${source}settings-permission-overlay.ts`,
      `${source}settings-render.ts`,
    ],
    typeOnlyAllowed: [],
    reason:
      'Keep settings commands independent of runs, routing, transports, the CLI, and worktrees.',
  },
  {
    name: 'settings-permission-boundary',
    file: `${source}settings-permission.ts`,
    allowed: [`${source}settings.ts`],
    typeOnlyAllowed: [],
    reason: 'Keep permission edits pure and independent of stores, commands, and transports.',
  },
  {
    name: 'settings-permission-overlay-boundary',
    file: `${source}settings-permission-overlay.ts`,
    allowed: ['shared/machine-config.ts', `${source}settings.ts`],
    typeOnlyAllowed: [],
    reason: 'Keep hosted and machine permission merging pure.',
  },
  {
    name: 'settings-machine-permissions-boundary',
    file: `${source}settings-machine-permissions.ts`,
    allowed: ['shared/machine-config.ts', 'orchestrator/src/run/run-process.ts'],
    typeOnlyAllowed: [],
    reason: 'Keep machine permission edits independent of CLI grammar and hosted settings.',
  },
  {
    name: 'settings-machine-apply-boundary',
    file: `${source}settings-machine-apply.ts`,
    allowed: [
      'bun:sqlite',
      'node:fs',
      'node:path',
      'shared/state-directory.ts',
      'shared/machine-config.ts',
      'orchestrator/src/canon/user-canon-home-files.ts',
      'orchestrator/src/database/db.ts',
      'orchestrator/src/doc/docs.ts',
      'orchestrator/src/project/project-lock.ts',
      'orchestrator/src/record/record-cache.ts',
      'orchestrator/src/run/run-process.ts',
      `${source}settings.ts`,
      `${source}settings-env.ts`,
      `${source}settings-files.ts`,
      `${source}settings-render.ts`,
      `${source}settings-permission-overlay.ts`,
      `${source}settings-write.ts`,
    ],
    typeOnlyAllowed: [],
    reason:
      'Keep machine settings application independent of CLI grammar, scheduling, and run lifecycle.',
  },
]
