import { dirname, normalize } from 'node:path'
import type { ArchitectureModule } from './architecture.ts'

const module = (file: string, allowed: string[]): ArchitectureModule => ({
  file,
  allowed: allowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
})

export const runLifecycleModules: ArchitectureModule[] = [
  module('orchestrator/src/run/synthetic-lifecycle-job.ts', []),
  module('orchestrator/src/run/run-resume-options.ts', [
    '../worktree/worktree-types.ts',
    './resume-tree.ts',
    './run-resume-kind.ts',
  ]),
  module('orchestrator/src/run/run-resume-claim.ts', [
    '../git/git-environment.ts',
    '../worktree/worktree-remove.ts',
    '../worktree/worktree-types.ts',
    './resume-tree.ts',
  ]),
  module('orchestrator/src/run/run-retry-claim.ts', [
    '../git/git-environment.ts',
    '../worktree/worktree.ts',
    '../worktree/worktree-types.ts',
    './branch-owner-guard.ts',
    './run-retry.ts',
  ]),
  module('orchestrator/src/run/run-alive.ts', []),
  module('orchestrator/src/run/branch-conversation-owner.ts', []),
  module('orchestrator/src/run/branch-owner-guard.ts', [
    '../database/db.ts',
    '../jobs/jobs.ts',
    './branch-conversation-owner.ts',
  ]),
  module('orchestrator/src/run/run-claim.ts', [
    '../agent/agents.ts',
    '../branch/create-time-settlement.ts',
    '../contract/codex-schema.ts',
    '../canon/canon.ts',
    '../git/checkout-identity.ts',
    '../contract/contract.ts',
    '../database/db.ts',
    '../dispatch/dispatch-preflight.ts',
    '../events.ts',
    '../route/failover.ts',
    '../git/git-environment.ts',
    '../sandbox/grok-trust.ts',
    '../worktree/keep-tree-hold.ts',
    '../mcp/mcp-preflight.ts',
    '../mcp/mcp-probe.ts',
    '../project/project-lock.ts',
    '../project/projects.ts',
    '../dispatch/prompt-retarget.ts',
    '../../../shared/record/schema.ts',
    '../resources/resource-claims.ts',
    '../resources/resource-ownership.ts',
    '../review/review-target.ts',
    './run-artifacts.ts',
    './question-close.ts',
    './branch-owner-guard.ts',
    './run-process.ts',
    './resume-tree.ts',
    '../sandbox/sandbox.ts',
    '../branch/task-branch.ts',
    '../worktree/worktree.ts',
    '../worktree/worktree-caller.ts',
    '../worktree/worktree-mcp.ts',
    '../worktree/worktree-preflight.ts',
    '../worktree/worktree-remove.ts',
    '../worktree/worktree-types.ts',
    './run-claim-plan.ts',
    './run-resume-kind.ts',
    './run-resume-options.ts',
    './run-resume-claim.ts',
    './run-retry-claim.ts',
    './run-task-reference.ts',
    './run-task-branch-resolution.ts',
    './run-worker-home.ts',
  ]),
  module('orchestrator/src/run/run-claim-plan.ts', ['./resume-tree.ts']),
  module('orchestrator/src/run/run-task-reference.ts', ['../../../shared/self-spawn.ts']),
  module('orchestrator/src/run/run-task-branch-resolution.ts', [
    '../branch/task-branch.ts',
    '../branch/task-branch-reuse.ts',
  ]),
  module('orchestrator/src/run/task-rulings.ts', ['./question-vocabulary.ts']),
  module('orchestrator/src/run/task-rulings-store.ts', ['../database/db.ts', './task-rulings.ts']),
  module('orchestrator/src/run/run-close.ts', [
    '../close/close-out.ts',
    '../contract/contract.ts',
    '../database/db.ts',
    '../route/failover.ts',
    '../failure/failure.ts',
    '../jobs/jobs.ts',
    '../worktree/keep-tree-hold.ts',
    '../mcp/mcp-preflight.ts',
    '../project/projects.ts',
    '../review/review-calibration.ts',
    '../route/route.ts',
    './question-close.ts',
    './run-process.ts',
    './run-types.ts',
    '../transport/transport.ts',
    '../worktree/worktree-remove.ts',
    '../worktree/worktree-types.ts',
  ]),
  module('orchestrator/src/run/run-lease.ts', [
    '../database/database-location.ts',
    '../project/project-lock.ts',
    './run-alive.ts',
  ]),
  module('orchestrator/src/run/run-live.ts', [
    '../agent/agents.ts',
    '../ask/ask.ts',
    './checkpoint.ts',
    './question-open.ts',
    '../sandbox/codex-mcp-scope.ts',
    '../confinement/confinement.ts',
    '../contract/contract.ts',
    '../database/db.ts',
    '../events.ts',
    '../failure/failure.ts',
    '../gate/gate-broker.ts',
    '../git/git-environment.ts',
    '../idle-kill.ts',
    '../jobs/jobs.ts',
    '../mailbox/mailbox-notice.ts',
    '../mailbox/mailbox.ts',
    '../live-outcome.ts',
    '../outcome.ts',
    '../project/project-lock.ts',
    './run-process.ts',
    './run-reply-source.ts',
    './run-resume-kind.ts',
    '../sandbox/sandbox.ts',
    '../transport/transport.ts',
    '../worktree/worktree-types.ts',
  ]),
  module('orchestrator/src/run/run-reply-source.ts', [
    '../contract/contract.ts',
    '../transport/transport.ts',
  ]),
  module('orchestrator/src/run/run-launch.ts', [
    '../route/failover.ts',
    '../transport/transport.ts',
  ]),
  module('orchestrator/src/run/run-worker-home.ts', [
    '../agent/agents.ts',
    '../recipe/tracked-recipe.ts',
    '../sandbox/codex-mcp-preflight.ts',
    '../sandbox/codex-mcp-scope.ts',
    '../sandbox/sandbox.ts',
    '../worktree/worktree-types.ts',
    './run-process.ts',
  ]),
  module('orchestrator/src/live-outcome.ts', [
    './failure/failure.ts',
    './outcome.ts',
    './run/run-process.ts',
    './transport/transport.ts',
  ]),
  module('orchestrator/src/run/run-terminal.ts', [
    '../ask/ask.ts',
    './checkpoint.ts',
    '../confinement/confinement.ts',
    '../contract/contract.ts',
    '../database/db.ts',
    '../evidence/evidence.ts',
    '../failure/failure.ts',
    '../idle-kill.ts',
    '../jobs/jobs.ts',
    '../record/machine-identity.ts',
    '../mcp/mcp-preflight.ts',
    '../outcome.ts',
    '../operator/operator-waiting.ts',
    '../project/projects.ts',
    '../resources/resource-ownership.ts',
    '../review/review.ts',
    './run-artifacts.ts',
    './run-liveness.ts',
    './run-outbox.ts',
    './run-process.ts',
    './run-resume-kind.ts',
    './question-vocabulary.ts',
    './question-close.ts',
    './question-outbox.ts',
    './run-terminal-blockers.ts',
    './run-terminal-premature.ts',
    './run-terminal-precedence.ts',
    '../sandbox/sandbox.ts',
    '../worktree/worktree-remove.ts',
    '../worktree/worktree-types.ts',
  ]),
  module('orchestrator/src/run/run-terminal-blockers.ts', ['../failure/failure.ts']),
  module('orchestrator/src/run/run-terminal-precedence.ts', [
    '../failure/failure.ts',
    '../outcome.ts',
  ]),
  module('orchestrator/src/run/run-types.ts', [
    '../contract/contract.ts',
    '../worktree/worktree-remove.ts',
    '../worktree/worktree-types.ts',
  ]),
]
