import { dirname, normalize } from 'node:path'
import type { ImportBoundary } from './architecture-boundaries.ts'

const boundary = (
  name: string,
  file: string,
  allowed: string[],
  reason: string,
  typeOnlyAllowed: string[] = [],
): ImportBoundary => ({
  name,
  file,
  allowed: allowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
  typeOnlyAllowed: typeOnlyAllowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
  reason,
})

export const runLifecycleBoundarySpecs: ImportBoundary[] = [
  boundary(
    'run-answer-boundary',
    'orchestrator/src/run/run-answer.ts',
    [
      'node:fs',
      '../../../shared/orch-contract.ts',
      '../../../shared/process-identity.ts',
      '../agent/agent-registry.ts',
      '../cli/args.ts',
      '../contract/contract.ts',
      '../caller-classification.ts',
      '../dashboard-capability.ts',
      '../database/db.ts',
      '../route/failover.ts',
      '../jobs/jobs.ts',
      '../worktree/keep-tree-hold.ts',
      '../mcp/mcp-preflight.ts',
      '../outcome.ts',
      '../workflow/autonomy.ts',
      '../workflow/autonomy-scopes.ts',
      './checkpoint.ts',
      './continuation-checkout-service.ts',
      './run.ts',
      './run-answer-liveness.ts',
      './run-answer-authority.ts',
      './run-artifacts.ts',
      './run-authority.ts',
      './run-control.ts',
      './run-dispatch.ts',
      './run-retry.ts',
      './run-retry-workspace.ts',
      './synthetic-lifecycle-job.ts',
      './question-delivery.ts',
      './question-open.ts',
      './question-outbox.ts',
      './question-vocabulary.ts',
      '../git/git-environment.ts',
    ],
    'Keep run-answer independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-artifacts-boundary',
    'orchestrator/src/run/run-artifacts.ts',
    [
      'node:fs',
      'node:path',
      '../artifact-paths.ts',
      '../database/database-location.ts',
      '../database/db.ts',
      '../database/migrations.ts',
      '../resources/resource-ownership.ts',
    ],
    'Keep run artifacts independent of routing, contracts, transports, reviews, and isolation.',
  ),
  boundary(
    'run-authority-boundary',
    'orchestrator/src/run/run-authority.ts',
    ['../caller-classification.ts', '../database/db.ts', './run-mutation-owner.ts', 'bun:sqlite'],
    'Enforce the run-authority concern boundary.',
  ),
  boundary(
    'run-control-boundary',
    'orchestrator/src/run/run-control.ts',
    [
      'node:fs',
      '../cli/args.ts',
      '../clock.ts',
      '../collect/collect.ts',
      '../database/db.ts',
      '../events.ts',
      '../route/failover.ts',
      '../git/checkout-identity.ts',
      '../git/git-environment.ts',
      '../jobs/jobs.ts',
      '../mcp/mcp-preflight.ts',
      '../outcome.ts',
      '../project/projects.ts',
      './continuation-checkpoint-context.ts',
      './continuation-checkout-service.ts',
      './continuation-tree-decision.ts',
      './continuation-tree-service.ts',
      './resume-tree.ts',
      './run.ts',
      './run-authority.ts',
      './run-dispatch.ts',
      './run-liveness.ts',
      './run-resume-kind.ts',
      './run-retry.ts',
      './checkpoint.ts',
      './question-open.ts',
    ],
    'Keep run-control independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-dispatch-boundary',
    'orchestrator/src/run/run-dispatch.ts',
    [
      'node:child_process',
      'node:crypto',
      'node:fs',
      '../../../shared/self-spawn.ts',
      '../../../shared/process-identity.ts',
      '../database/db.ts',
      '../dispatch/dispatch-preflight.ts',
      '../jobs/jobs.ts',
      '../mcp/mcp-preflight.ts',
      '../project/projects.ts',
      '../record/record-attribution.ts',
      './run.ts',
      './run-alive.ts',
      './run-artifacts.ts',
      './run-coordinator-log.ts',
      './run-lease.ts',
      './run-mcp-main-stack.ts',
      './run-resume-kind.ts',
      '../route/failover.ts',
    ],
    'Keep run-dispatch independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-inbox-boundary',
    'orchestrator/src/run/run-inbox.ts',
    [
      '../database/db.ts',
      '../evidence/evidence-query.ts',
      '../project/projects.ts',
      '../workflow/autonomy-scopes.ts',
      '../workflow/workflow-cursor-format.ts',
      './question-vocabulary.ts',
      './question-open.ts',
      './run-answer-liveness.ts',
    ],
    'Keep run inbox independent of run control, transports, routing, the CLI, and worktrees.',
  ),
  boundary(
    'run-listing-boundary',
    'orchestrator/src/run/run-listing.ts',
    [
      '../collect/collect.ts',
      '../database/db.ts',
      '../evidence/evidence-query.ts',
      '../outcome.ts',
      '../events.ts',
      '../idle-kill.ts',
      './live-run-member.ts',
      './question-open.ts',
      './synthetic-lifecycle-job.ts',
    ],
    'Keep run listing independent of run control, transports, routing, the CLI, and worktrees.',
    ['./question-vocabulary.ts'],
  ),
  boundary(
    'run-liveness-boundary',
    'orchestrator/src/run/run-liveness.ts',
    [
      '../database/db.ts',
      '../../../shared/process-identity.ts',
      '../resources/resource-ownership.ts',
      './run-alive.ts',
      './run-authority.ts',
      './run-bootstrap.ts',
      './run-coordinator-log.ts',
      './run-lease.ts',
      './question-close.ts',
      './question-open.ts',
      'bun:sqlite',
    ],
    'Enforce the run-liveness concern boundary.',
  ),
  boundary(
    'run-outbox-boundary',
    'orchestrator/src/run/run-outbox.ts',
    [
      '../../../shared/record/schema.ts',
      '../record/outbox-sanitize.ts',
      './synthetic-lifecycle-job.ts',
      'bun:sqlite',
    ],
    'Enforce the run-outbox concern boundary.',
  ),
  boundary(
    'run-process-boundary',
    'orchestrator/src/run/run-process.ts',
    [
      'node:crypto',
      './checkpoint.ts',
      '../database/db.ts',
      '../dispatch/dispatch-preflight.ts',
      '../idle-kill.ts',
      '../agent/agent-registry.ts',
      '../agent/worker-launch-env.ts',
    ],
    'Keep run process control independent of routing, contracts, reviews, and transports.',
  ),
]
