import { dirname, normalize } from 'node:path'
import { branchStoreModuleSpecs } from './architecture-branch-store.ts'
import { canonBoundarySpecs } from './architecture-canon-boundaries.ts'
import { databaseBoundarySpecs } from './architecture-database-boundaries.ts'
import { mcpBoundarySpecs } from './architecture-mcp-boundaries.ts'
import {
  recordReadBoundariesAfterPublish,
  recordReadBoundariesBeforePublish,
  recordSchemaBoundaries,
} from './architecture-record-boundaries.ts'
import { recordSettingsBoundarySpecs } from './architecture-record-settings-boundaries.ts'
import { reviewBoundarySpecs } from './architecture-review-boundaries.ts'
import { runModuleBoundarySpecs } from './architecture-run-modules.ts'
import { runRetryBoundarySpecs } from './architecture-run-retry.ts'
import { runStopBoundarySpecs } from './architecture-run-stop.ts'
import { settingsBoundarySpecs } from './architecture-settings-boundaries.ts'
import { setupModuleSpecs } from './architecture-setup-modules.ts'

const landing = '../landing-tree/landing-tree.ts'

const normalizeTarget = (file: string, target: string) =>
  target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target

export type ImportBoundary = {
  name: string
  file: string
  allowed: string[]
  typeOnlyAllowed: string[]
  reason: string
}

const boundary = (
  name: string,
  file: string,
  allowed: string[],
  reason: string,
  typeOnlyAllowed: string[] = [],
): ImportBoundary => ({
  name,
  file,
  allowed: allowed.map((target) => normalizeTarget(file, target)),
  typeOnlyAllowed: typeOnlyAllowed.map((target) => normalizeTarget(file, target)),
  reason,
})

// Each row lists every import its file may use; anything else fails check-architecture.
// Widen a row deliberately, with its reason still true, rather than routing around it.
export const importBoundaries: ImportBoundary[] = [
  // biome-ignore format: compact extracted boundary registration keeps this frozen manifest from growing.
  ...runRetryBoundarySpecs.map((spec) => boundary(spec.name, spec.file, [...spec.allowed], spec.reason)),
  ...runModuleBoundarySpecs.map((spec) =>
    boundary(spec.name, spec.file, [...spec.allowed], spec.reason),
  ),
  ...branchStoreModuleSpecs.map((spec) =>
    boundary(spec.name, spec.file, [...spec.allowed], spec.reason),
  ),
  boundary(
    'code-commands-boundary',
    'orchestrator/src/code/code-commands.ts',
    ['../project/projects.ts', './code-search.ts'],
    'Keep code search commands independent of stores, transports, and retrieval internals.',
  ),
  boundary(
    'agent-commands-boundary',
    'orchestrator/src/agent/agent-commands.ts',
    [
      './agent-probe.ts',
      './agent-registry.ts',
      '../cli/args.ts',
      '../database/db.ts',
      './model-host.ts',
    ],
    'Keep agent registry command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  // biome-ignore format: compact declaration keeps this frozen manifest shrinking.
  boundary('canon-budget-boundary', 'orchestrator/src/canon/canon-budget.ts', [], 'Keep canon budget policy independent of every adapter and store.'),
  boundary(
    'canon-files-boundary',
    'orchestrator/src/canon/canon-files.ts',
    ['node:fs', 'node:path', '../../../shared/git.ts', './canon-lint.ts', './codex-project-doc.ts'],
    'Keep canon file collection independent of stores, commands, runs, routing, transports, and worktrees.',
  ),
  boundary(
    'canon-hydrate-boundary',
    'orchestrator/src/canon/canon-hydrate.ts',
    ['node:path', './canon-lint.ts', './codex-project-doc.ts', './user-canon-home.ts'],
    'Keep canon hydration planning pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'canon-lint-boundary',
    'orchestrator/src/canon/canon-lint.ts',
    [
      'node:path',
      'github-slugger',
      '../../../shared/canon-references.ts',
      '../../../shared/ratchet.ts',
      ...['./canon-budget.ts', './codex-project-doc.ts', './prose-lint.ts'],
    ],
    'Keep canon lint decisions pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'prose-lint-boundary',
    'orchestrator/src/canon/prose-lint.ts',
    [],
    'Keep shared prose lint decisions pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'canon-write-gate-boundary',
    'orchestrator/src/canon/canon-write-gate.ts',
    [
      'node:path',
      './canon-hydrate.ts',
      './canon-lint.ts',
      './canon-load.ts',
      './user-canon-home.ts',
    ],
    'Keep canon write decisions pure and independent of filesystems, stores, commands, and processes.',
  ),
  ...canonBoundarySpecs,
  ...settingsBoundarySpecs,
  boundary(
    'checkout-identity-boundary',
    'orchestrator/src/git/checkout-identity.ts',
    ['node:fs', 'node:path', './git-environment.ts', '../project/projects.ts'],
    'Keep checkout addressing independent of databases and lifecycle policy.',
  ),
  boundary(
    'cleanup-boundary',
    'orchestrator/src/cleanup/cleanup.ts',
    [
      'node:fs',
      'node:path',
      '../database/db.ts',
      '../resources/docker-resources.ts',
      '../evidence/evidence-query.ts',
      '../git/git-environment.ts',
      '../project/project-lock.ts',
      '../project/projects.ts',
      '../resources/resource-claims.ts',
      '../resources/resource-ownership.ts',
      '../run/run-authority.ts',
      '../worktree/worktree-attribution.ts',
      '../worktree/worktree-remove.ts',
      '../worktree/worktree-types.ts',
      './branch-deletion-provenance.ts',
    ],
    'Keep cleanup independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'cleanup-sweep-boundary',
    'orchestrator/src/cleanup/cleanup-sweep.ts',
    [
      'node:fs',
      'node:path',
      './cleanup.ts',
      './cleanup-sweep-decisions.ts',
      './cleanup-sweep-reclaim.ts',
      './cleanup-sweep-residue.ts',
      './reader-clone-archive-retention.ts',
      './claim-reconciliation.ts',
      '../close/close-out.ts',
      '../database/db.ts',
      '../evidence/unjudged-expiry.ts',
      '../resources/docker-resources.ts',
      '../hook-tree/hook-tree.ts',
      '../landing-tree/release-observation.ts',
      '../../../shared/process-identity.ts',
      '../project/projects.ts',
      '../resources/resource-ownership.ts',
      '../run/run-alive.ts',
      '../run/run-artifacts.ts',
      '../run/run-authority.ts',
      '../run/run-lease.ts',
      '../run/synthetic-lifecycle-job.ts',
      '../sandbox/grok-trust.ts',
      '../worktree/worktree-attribution.ts',
      '../worktree/worktree-remove.ts',
      '../worktree/worktree-types.ts',
    ],
    'Keep cleanup-sweep independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'cleanup-sweep-decisions-boundary',
    'orchestrator/src/cleanup/cleanup-sweep-decisions.ts',
    [],
    'Keep cleanup sweep decisions pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'close-out-boundary',
    'orchestrator/src/close/close-out.ts',
    // biome-ignore format: compact entries keep the frozen boundary manifest within its ceiling.
    [
      'node:fs',
      'node:path',
      './absent-close-out-residue.ts',
      './absent-tree-close-out.ts',
      './close-out-adoption.ts',
      './close-out-questions.ts', './close-out-report.ts',
      './conversation-liveness.ts', './close-out-release-holds.ts', './reader-scratch-close-out.ts',
      './retained-branch.ts',
      '../database/db.ts',
      '../git/git-environment.ts',
      '../hook-tree/hook-tree.ts',
      landing,
      '../idle-kill.ts',
      '../worktree/keep-tree-hold.ts',
      '../../../shared/process-identity.ts',
      '../project/project-lock.ts',
      '../project/projects.ts',
      '../reclaim/reclaim.ts',
      '../resources/resource-claims.ts',
      '../resources/resource-ownership.ts',
      '../run/run-alive.ts',
      '../run/run-artifacts.ts',
      '../run/run-lease.ts',
      '../run/run-process.ts',
      '../run/synthetic-lifecycle-job.ts',
      '../worktree/worktree.ts',
      '../worktree/worktree-attribution.ts',
      '../worktree/worktree-remove.ts',
      '../worktree/worktree-types.ts',
    ],
    'Keep close-out independent of routing, contracts, transports, reviews, and the CLI.',
  ),
  boundary(
    'confinement-ruling-boundary',
    'orchestrator/src/confinement/confinement-ruling.ts',
    [
      'node:fs',
      './confinement.ts',
      '../database/db.ts',
      '../git/git-environment.ts',
      '../project/projects.ts',
      '../run/run-authority.ts',
      '../run/run-liveness.ts',
    ],
    'Keep confinement rulings independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'contract-boundary',
    'orchestrator/src/contract/contract.ts',
    ['../jobs/jobs.ts', '../outcome.ts', '../review/review-vocabulary.ts', '../run/checkpoint.ts'],
    'Keep reply dialect resolution independent of lifecycle and impure transport concerns.',
  ),
  ...databaseBoundarySpecs,
  boundary(
    'dispatch-commands-boundary',
    'orchestrator/src/dispatch/dispatch-commands.ts',
    [
      'node:fs',
      './dispatch-preflight.ts',
      './execution-requirement.ts',
      './review-lens-prompt.ts',
      '../jobs/jobs.ts',
      '../lens/lenses.ts',
      '../worktree/keep-tree-hold.ts',
      '../project/projects.ts',
      '../route/failover.ts',
      '../mcp/mcp-preflight.ts',
    ],
    'Keep dispatch command adapters independent of transports, routing, worktrees, the CLI, and reviews.',
  ),
  boundary(
    'execution-requirement-boundary',
    'orchestrator/src/dispatch/execution-requirement.ts',
    [],
    'Keep execution requirement admission a pure decision over declared execution and tree kind.',
  ),
  boundary(
    'dispatch-preflight-boundary',
    'orchestrator/src/dispatch/dispatch-preflight.ts',
    [
      '../cli/args.ts',
      '../git/checkout-identity.ts',
      '../database/db.ts',
      '../git/git-environment.ts',
      '../jobs/jobs.ts',
      '../lens/lenses.ts',
      '../project/projects.ts',
      '../review/review-target.ts',
      '../worktree/worktree-caller.ts',
      '../worktree/worktree-preflight.ts',
      '../worktree/worktree-template.ts',
    ],
    'Keep dispatch admission independent of transports, routing, and contracts.',
  ),
  boundary(
    'review-lens-prompt-boundary',
    'orchestrator/src/dispatch/review-lens-prompt.ts',
    [],
    'Keep review-lens prompt composition a pure decision over lens text and supplied prompt.',
  ),
  boundary(
    'doc-commands-boundary',
    'orchestrator/src/doc/doc-commands.ts',
    ['node:fs', '../canon/canon.ts', './doc-canon-tree.ts', './doc-search.ts', './docs.ts'],
    'Keep doc commands independent of database writes beyond docs, runs, routing, transports, and the CLI.',
  ),
  boundary(
    'doc-lint-boundary',
    'orchestrator/src/doc/doc-lint.ts',
    ['../../../shared/docs.ts', '../canon/canon-lint.ts', '../canon/prose-lint.ts'],
    'Keep document lint decisions pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'local-doc-revisions-boundary',
    'orchestrator/src/doc/doc-revision-store.ts',
    ['../database/db.ts', './doc-write-allowed.ts'],
    'Keep local revision ordering and compare-and-set facts independent of hosted transport and CLI.',
  ),
  boundary(
    'doc-write-allowed-boundary',
    'orchestrator/src/doc/doc-write-allowed.ts',
    [
      '../canon/canon-hydrate.ts',
      '../canon/canon-write-gate.ts',
      '../canon/pack-budget.ts',
      '../canon/canon-lint.ts',
      '../settings/settings.ts',
      '../../../shared/docs.ts',
      './doc-lint.ts',
    ],
    'Keep document write decisions independent of stores, HTTP, filesystems, and CLI.',
  ),
  boundary(
    'doctor-boundary',
    'orchestrator/src/health/doctor.ts',
    [
      'node:fs',
      '../../../shared/brand.ts',
      '../agent/agent-auth.ts',
      '../agent/agent-registry.ts',
      '../agent/agents.ts',
      '../score/agreement.ts',
      '../database/db.ts',
      '../resources/docker-resources.ts',
      '../evidence/evidence-query.ts',
      '../worktree/keep-tree-hold.ts',
      '../agent/model-host.ts',
      '../resources/resource-claims.ts',
      '../resources/resource-ownership.ts',
      '../score/score.ts',
      '../worktree/worktree-attribution.ts',
      '../worktree/worktree-lifecycle.ts',
      '../canon/canon.ts',
      '../doc/docs.ts',
      '../canon/pack-budget.ts',
      '../canon/evals.ts',
      '../sandbox/sandbox.ts',
      '../sandbox/sandbox-runtime.ts',
      '../database/migrations.ts',
      './health.ts',
      '../project/projects.ts',
    ],
    'Keep doctor independent of transports, routing, run control, the CLI, and reviews by value.',
  ),
  boundary(
    'duel-boundary',
    'orchestrator/src/score/duel.ts',
    ['../database/db.ts', '../evidence/evidence-query.ts', './score.ts'],
    'Enforce the duel concern boundary.',
  ),
  boundary(
    'epic-commands-boundary',
    'orchestrator/src/epic/epic-commands.ts',
    ['./epic.ts'],
    'Keep epic command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'evidence-boundary',
    'orchestrator/src/evidence/evidence.ts',
    ['../contract/contract.ts', '../mcp/mcp-preflight.ts', '../review/review-triage.ts'],
    'Keep evidence assessment independent of execution and transaction ownership.',
    ['bun:sqlite', '../outcome.ts', '../review/review.ts'],
  ),
  boundary(
    'evidence-query-boundary',
    'orchestrator/src/evidence/evidence-query.ts',
    // biome-ignore format: compact dependency list keeps this manifest within its frozen file ceiling.
    ['../database/db.ts', '../failure/failure.ts', '../run/synthetic-lifecycle-job.ts', 'bun:sqlite'],
    'Enforce the evidence-query concern boundary.',
  ),
  boundary(
    'failover-boundary',
    'orchestrator/src/route/failover.ts',
    [
      '../agent/agent-registry.ts',
      '../database/db.ts',
      'bun:sqlite',
      '../worktree/keep-tree-hold.ts',
      '../mcp/mcp-preflight.ts',
      '../run/resume-tree.ts',
      '../run/question-open.ts',
    ],
    'Keep failover independent of execution transports, contracts, and worktrees.',
  ),
  boundary(
    'failure-commands-boundary',
    'orchestrator/src/failure/failure-commands.ts',
    ['../database/db.ts', './failure.ts', '../run/run-authority.ts'],
    'Keep failure command adapters independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  boundary(
    'git-environment-boundary',
    'orchestrator/src/git/git-environment.ts',
    ['node:crypto', 'node:fs', 'node:os', 'node:path', '../../../shared/git.ts'],
    'Keep hermetic git observation independent of lifecycle and policy concerns.',
  ),
  boundary(
    'health-commands-boundary',
    'orchestrator/src/health/health-commands.ts',
    ['../../../shared/orch-contract.ts', '../database/db.ts', './health.ts'],
    'Keep health command adapters independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  boundary(
    'hosted-hub-server-boundary',
    'hub/src/hosted.ts',
    [
      'node:fs',
      'node:url',
      '@trpc/server/adapters/fetch',
      './app-static.ts',
      './evidence-api.ts',
      './hosted-health.ts',
      './note-api.ts',
      './operator-waiting-email-api.ts',
      './report-api.ts',
      './task-api.ts',
      './trpc/context.ts',
      './trpc/hosted-router.ts',
    ],
    'Enforce the hosted hub server concern boundary.',
  ),
  boundary(
    'isolation-boundary',
    'orchestrator/src/worktree/worktree.ts',
    [
      'node:fs',
      './worktree-create.ts',
      './worktree-readonly.ts',
      '../project/projects.ts',
      './worktree-types.ts',
    ],
    'Keep the isolation module independent of run policy and lifecycle concerns.',
  ),
  boundary(
    'issue-report-fields-boundary',
    'orchestrator/src/issue/issue-report-fields.ts',
    [],
    'Keep issue report field decisions pure and independent of adapters.',
  ),
  boundary(
    'job-commands-boundary',
    'orchestrator/src/jobs/job-commands.ts',
    ['./jobs.ts'],
    'Keep job catalogue command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'judgment-boundary',
    'orchestrator/src/judgment.ts',
    [
      'node:fs',
      '../../shared/record/schema.ts',
      './database/db.ts',
      './evidence/unjudged-expiry.ts',
      './score/duel.ts',
      './jobs/jobs.ts',
      './record/machine-identity.ts',
      './review/review.ts',
      './review/review-outbox.ts',
      './review/review-triage.ts',
      './review/review-vocabulary.ts',
      './run/run-authority.ts',
      './run/question-close.ts',
      './run/run-outbox.ts',
      './run/synthetic-lifecycle-job.ts',
      './score/score.ts',
      './score/score-outbox.ts',
      './verdict/verdict-rules.ts',
    ],
    'Keep judgment independent of transports, worktrees, routing, the CLI, durable execution, dispatch, and cleanup.',
  ),
  boundary(
    'landing-outbox-boundary',
    'orchestrator/src/record/landing-outbox.ts',
    ['../../../shared/record/schema.ts', './outbox-sanitize.ts', 'bun:sqlite'],
    'Enforce the landing-outbox concern boundary.',
  ),
  boundary(
    'machine-identity-boundary',
    'orchestrator/src/record/machine-identity.ts',
    ['node:os', '../../../shared/record/schema.ts', '../database/db.ts'],
    'Enforce the machine-identity concern boundary.',
  ),
  ...mcpBoundarySpecs,
  boundary(
    'metric-commands-boundary',
    'orchestrator/src/metric/metric-commands.ts',
    ['./metric.ts'],
    'Keep metric command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'monitor-commands-boundary',
    'orchestrator/src/monitor/monitor-commands.ts',
    [
      'node:crypto',
      'node:fs',
      'node:path',
      '../../../shared/install-root.ts',
      '../../../shared/monitor-capability.ts',
      '../../../shared/process-identity.ts',
      '../database/db.ts',
      '../canon/evals.ts',
      './monitor.ts',
      './monitor-notices.ts',
      './monitor-store-write-lock.ts',
      './monitor-types.ts',
    ],
    'Keep monitor command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'outcome-boundary',
    'orchestrator/src/outcome.ts',
    [],
    'Keep outcome decisions and interpretation independent of lifecycle concerns.',
  ),
  boundary(
    'port-commands-boundary',
    'orchestrator/src/porting/port-commands.ts',
    [
      'node:fs',
      'node:path',
      '../database/db.ts',
      './porting.ts',
      './porting-import.ts',
      '../project/projects.ts',
    ],
    'Keep port commands independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  ...recordSchemaBoundaries,
  boundary(
    'project-commands-boundary',
    'orchestrator/src/project/project-commands.ts',
    [
      'node:fs',
      '../database/db.ts',
      '../lens/lenses.ts',
      './projects.ts',
      '../worktree/worktree-lifecycle.ts',
      '../worktree/worktree-template.ts',
    ],
    'Keep project commands independent of runs, routing, transports, reviews, the CLI, and worktrees by value.',
  ),
  boundary(
    'prompt-retarget-boundary',
    'orchestrator/src/dispatch/prompt-retarget.ts',
    ['../git/checkout-identity.ts'],
    'Keep prompt retargeting independent of database, transport, contract, and routing concerns.',
  ),
  boundary(
    'recalibration-boundary',
    'orchestrator/src/score/recalibration.ts',
    [
      'node:fs',
      'node:readline/promises',
      './agreement.ts',
      '../database/db.ts',
      '../jobs/jobs.ts',
      './score.ts',
      'node:stream',
    ],
    'Keep recalibration independent of transports, worktrees, routing, the CLI, durable execution, dispatch, and cleanup.',
  ),
  boundary(
    'recipe-lifecycle-boundary',
    'orchestrator/src/recipe/recipe-lifecycle.ts',
    ['./recipe-schema.ts', './recipe-step.ts'],
    'Keep lifecycle planning pure and independent of execution, persistence, filesystem, and the register.',
  ),
  boundary(
    'recipe-loader-boundary',
    'orchestrator/src/recipe/recipe-loader.ts',
    ['node:fs', 'node:path', './recipe-schema.ts'],
    'Keep tracked recipe loading independent of execution, persistence, and CLI concerns.',
  ),
  boundary(
    'recipe-schema-boundary',
    'orchestrator/src/recipe/recipe-schema.ts',
    ['zod'],
    'Keep the recipe schema pure and independent of file, register, and execution concerns.',
  ),
  boundary(
    'recipe-step-boundary',
    'orchestrator/src/recipe/recipe-step.ts',
    ['node:path', '../worktree/worktree-template.ts', './recipe-schema.ts'],
    'Keep recipe step execution independent of lifecycle, persistence, claims, and register concerns.',
  ),
  boundary(
    'record-api-boundary',
    'orchestrator/src/record/record-api.ts',
    [
      'hono',
      'hono/cors',
      'zod',
      '../verdict/verdict-payload.ts',
      '../verdict/verdict-rules.ts',
      './record-config.ts',
      './record-auth.ts',
      './record-docs.ts',
      './record-snapshots.ts',
      './record-verdicts.ts',
      './record-projects.ts',
      './record-runs.ts',
      './record-runs-window-query.ts',
      './record-api-projects.ts',
      './record-api-doc-schemas.ts',
      './record-api-settings.ts',
      './record-settings.ts',
    ],
    'Enforce the record-api concern boundary.',
  ),
  boundary(
    'record-api-projects-boundary',
    'orchestrator/src/record/record-api-projects.ts',
    ['hono', 'zod', './record-auth.ts', './record-projects.ts'],
    'Keep hosted project routes independent of SQL and local execution.',
  ),
  ...recordSettingsBoundarySpecs,
  boundary(
    'record-project-write-boundary',
    'orchestrator/src/record/record-project-write.ts',
    [],
    'Keep the hosted project rename decision pure and independent of SQL, HTTP, and stores.',
  ),
  boundary(
    'record-api-client-boundary',
    'orchestrator/src/record/record-api-client.ts',
    [
      '../doc/doc-write-allowed.ts',
      '../verdict/verdict-payload.ts',
      './record-auth.ts',
      './record-session.ts',
      './record-snapshots.ts',
      './record-settings.ts',
    ],
    'Enforce the record API client concern boundary.',
    ['../canon/canon-lint.ts'],
  ),
  boundary(
    'record-api-server-boundary',
    'orchestrator/src/record/record-api-server.ts',
    [
      '../postgres/postgres-migrate.ts',
      './record-config.ts',
      './record-api.ts',
      './record-auth.ts',
      './record-docs.ts',
      './record-projects.ts',
      './record-reviews.ts',
      './record-runs.ts',
      './record-snapshots.ts',
      './record-settings.ts',
      './record-verdicts.ts',
    ],
    'Enforce the record-api-server concern boundary.',
  ),
  boundary(
    'record-auth-command-boundary',
    'orchestrator/src/record/record-auth-command.ts',
    ['../../../shared/record-session.ts', './record-auth.ts', './record-session.ts'],
    'Enforce the record-auth-command concern boundary.',
  ),
  boundary(
    'record-cache-boundary',
    'orchestrator/src/record/record-cache.ts',
    ['../database/db.ts', './record-api-client.ts', 'bun:sqlite'],
    'Enforce the record-cache concern boundary.',
  ),
  ...recordReadBoundariesBeforePublish,
  boundary(
    'record-publish-boundary',
    'orchestrator/src/record/record-publish.ts',
    [
      '../agent/agent-commands.ts',
      '../health/health-commands.ts',
      '../jobs/job-commands.ts',
      './machine-identity.ts',
      './record-api-client.ts',
      './record-snapshots.ts',
      '../state/serve.ts',
    ],
    'Enforce that snapshot publishing composes only the existing view services and record client.',
  ),
  boundary(
    'record-push-docs-boundary',
    'orchestrator/src/record/record-push-docs.ts',
    ['../database/db.ts', './record-api-client.ts', '../doc/doc-write-allowed.ts'],
    'Enforce the record-push-docs concern boundary.',
  ),
  ...recordReadBoundariesAfterPublish,
  boundary(
    'record-sync-boundary',
    'orchestrator/src/record/record-sync.ts',
    // biome-ignore format: compact dependency list keeps this manifest within its frozen file ceiling.
    [
      'bun', 'drizzle-orm/bun-sql', 'drizzle-orm',
      '../../../shared/record/schema.ts', '../../../shared/record/schema-landing.ts',
      '../../../shared/record/schema-review.ts', '../../../shared/record/schema-run.ts',
      '../../../shared/record/schema-question.ts', '../../../shared/record-space-membership.ts',
      '../database/db.ts',
      './landing-outbox.ts',
      './machine-identity.ts',
      './outbox-dependency.ts', './outbox-failure.ts', './outbox-quarantine.ts',
      './outbox-payload-contracts.ts',
      './record-cache.ts',
      './record-review-read.ts',
      './record-review-values.ts',
      './record-session.ts',
      './record-sync-types.ts',
      '../review/review-outbox.ts',
      '../run/run-outbox.ts',
      '../run/question-outbox.ts',
      '../score/score-outbox.ts',
      '../verdict/verdict-rules.ts',
      './score-sync.ts',
      'bun:sqlite',
    ],
    'Enforce the record-sync concern boundary.',
  ),
  boundary(
    'score-sync-boundary',
    'orchestrator/src/record/score-sync.ts',
    [
      'bun',
      'drizzle-orm/bun-sql',
      '../../../shared/record/schema-run.ts',
      '../verdict/verdict-payload.ts',
      './record-sync-types.ts',
      './record-verdicts.ts',
    ],
    'Keep hosted score validation and upsert together.',
  ),
  boundary(
    'record-sync-command-boundary',
    'orchestrator/src/record/record-sync-command.ts',
    ['../../../shared/machine-config.ts', './record-sync.ts', './record-tunnel-error.ts'],
    'Enforce the record-sync-command concern boundary.',
  ),
  boundary(
    'record-review-read-boundary',
    'orchestrator/src/record/record-review-read.ts',
    [],
    'Keep hosted review-read value mapping independent of record delivery.',
  ),
  boundary(
    'record-review-values-boundary',
    'orchestrator/src/record/record-review-values.ts',
    [],
    'Keep hosted review value mapping independent of record delivery.',
  ),
  boundary(
    'resource-ownership-boundary',
    'orchestrator/src/resources/resource-ownership.ts',
    [
      'node:fs',
      'node:path',
      '../git/checkout-identity.ts',
      '../database/database-location.ts',
      '../database/db.ts',
      './docker-resources.ts',
      '../evidence/evidence-query.ts',
      '../git/git-environment.ts',
      '../../../shared/process-identity.ts',
      '../project/project-lock.ts',
      '../run/run-alive.ts',
      '../run/run-lease.ts',
      'bun:sqlite',
    ],
    'Enforce the resource-ownership concern boundary.',
  ),
  ...reviewBoundarySpecs.map((spec) =>
    boundary(spec.name, spec.file, spec.allowed, spec.reason, spec.typeOnlyAllowed),
  ),
  boundary(
    'routing-commands-boundary',
    'orchestrator/src/route/routing-commands.ts',
    [
      '../score/agreement.ts',
      '../score/duel.ts',
      '../state/guide.ts',
      '../lens/lenses.ts',
      '../project/projects.ts',
      './route.ts',
      './routing-backtest.ts',
    ],
    'Keep routing command adapters independent of runs, transports, the CLI, worktrees, and reviews by value.',
  ),
  boundary(
    'run-answer-boundary',
    'orchestrator/src/run/run-answer.ts',
    [
      'node:fs',
      '../../../shared/orch-contract.ts',
      '../../../shared/process-identity.ts',
      '../agent/agent-registry.ts',
      '../cli/args.ts',
      '../contract/contract.ts',
      '../dashboard-capability.ts',
      '../database/db.ts',
      '../route/failover.ts',
      '../jobs/jobs.ts',
      '../worktree/keep-tree-hold.ts',
      '../mcp/mcp-preflight.ts',
      '../outcome.ts',
      '../workflow/autonomy.ts',
      '../workflow/autonomy-scopes.ts',
      './checkpoint.ts',
      './run.ts',
      './run-answer-liveness.ts',
      './run-answer-authority.ts',
      './run-artifacts.ts',
      './run-authority.ts',
      './run-control.ts',
      './run-dispatch.ts',
      './run-retry.ts',
      './run-retry-workspace.ts',
      './synthetic-lifecycle-job.ts',
      './question-delivery.ts',
      './question-open.ts',
      './question-outbox.ts',
      './question-vocabulary.ts',
      '../git/git-environment.ts',
    ],
    'Keep run-answer independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-artifacts-boundary',
    'orchestrator/src/run/run-artifacts.ts',
    [
      'node:fs',
      'node:path',
      '../artifact-paths.ts',
      '../database/database-location.ts',
      '../database/db.ts',
      '../database/migrations.ts',
      '../resources/resource-ownership.ts',
    ],
    'Keep run artifacts independent of routing, contracts, transports, reviews, and isolation.',
  ),
  boundary(
    'run-authority-boundary',
    'orchestrator/src/run/run-authority.ts',
    ['../database/db.ts', './run-mutation-owner.ts', 'bun:sqlite'],
    'Enforce the run-authority concern boundary.',
  ),
  // biome-ignore format: compact dependency list keeps this manifest within its frozen file ceiling.
  boundary(
    'run-control-boundary',
    'orchestrator/src/run/run-control.ts',
    [
      'node:fs',
      '../cli/args.ts',
      '../clock.ts',
      '../collect/collect.ts',
      '../database/db.ts',
      '../events.ts',
      '../route/failover.ts',
      '../git/checkout-identity.ts',
      '../git/git-environment.ts',
      '../jobs/jobs.ts',
      '../mcp/mcp-preflight.ts',
      '../outcome.ts',
      '../project/projects.ts',
      './continuation-checkpoint-context.ts',
      './resume-tree.ts', './run.ts', './run-authority.ts', './run-dispatch.ts', './run-liveness.ts', './run-resume-kind.ts', './run-retry.ts', './checkpoint.ts', './question-open.ts',
    ],
    'Keep run-control independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  // biome-ignore format: compact dependency list keeps this manifest within its frozen file ceiling.
  boundary(
    'run-dispatch-boundary',
    'orchestrator/src/run/run-dispatch.ts',
    [
      'node:child_process',
      'node:crypto',
      'node:fs',
      '../../../shared/self-spawn.ts',
      '../../../shared/process-identity.ts',
      '../database/db.ts',
      '../dispatch/dispatch-preflight.ts',
      '../jobs/jobs.ts',
      '../mcp/mcp-preflight.ts',
      '../project/projects.ts',
      '../record/record-attribution.ts',
      './run.ts', './run-alive.ts', './run-artifacts.ts', './run-coordinator-log.ts', './run-lease.ts', './run-resume-kind.ts', '../route/failover.ts',
    ],
    'Keep run-dispatch independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-inbox-boundary',
    'orchestrator/src/run/run-inbox.ts',
    [
      '../database/db.ts',
      '../evidence/evidence-query.ts',
      '../project/projects.ts',
      '../workflow/autonomy-scopes.ts',
      './question-vocabulary.ts',
      './question-open.ts',
      './run-answer-liveness.ts',
    ],
    'Keep run inbox independent of run control, transports, routing, the CLI, and worktrees.',
  ),
  // biome-ignore format: Keep this boundary declaration within the frozen architecture manifest ceiling.
  boundary('live-run-member-boundary', 'orchestrator/src/run/live-run-member.ts', ['bun:sqlite', '../../../shared/process-identity.ts', '../database/db.ts', '../events.ts', '../idle-kill.ts', '../jobs/jobs.ts', '../stalled-run.ts'], 'Keep the canonical live member and its stall observation independent of adapters.'),
  boundary(
    'run-listing-boundary',
    'orchestrator/src/run/run-listing.ts',
    [
      '../collect/collect.ts',
      '../database/db.ts',
      '../evidence/evidence-query.ts',
      '../outcome.ts',
      '../events.ts',
      '../idle-kill.ts',
      './live-run-member.ts',
      './question-open.ts',
      './synthetic-lifecycle-job.ts',
    ],
    'Keep run listing independent of run control, transports, routing, the CLI, and worktrees.',
    ['./question-vocabulary.ts'],
  ),
  // biome-ignore format: Keep this boundary declaration within the frozen architecture manifest ceiling.
  boundary('run-liveness-boundary', 'orchestrator/src/run/run-liveness.ts', ['../database/db.ts', '../../../shared/process-identity.ts', '../resources/resource-ownership.ts', './run-alive.ts', './run-authority.ts', './run-bootstrap.ts', './run-coordinator-log.ts', './run-lease.ts', './question-close.ts', './question-open.ts', 'bun:sqlite'], 'Enforce the run-liveness concern boundary.'),
  // biome-ignore format: Keep this boundary declaration within the frozen architecture manifest ceiling.
  boundary('run-outbox-boundary', 'orchestrator/src/run/run-outbox.ts', ['../../../shared/record/schema.ts', '../record/outbox-sanitize.ts', './synthetic-lifecycle-job.ts', 'bun:sqlite'], 'Enforce the run-outbox concern boundary.'),
  boundary(
    'run-process-boundary',
    'orchestrator/src/run/run-process.ts',
    [
      'node:crypto',
      './checkpoint.ts',
      '../database/db.ts',
      '../dispatch/dispatch-preflight.ts',
      '../idle-kill.ts',
      '../agent/agent-registry.ts',
      '../agent/worker-launch-env.ts',
    ],
    'Keep run process control independent of routing, contracts, reviews, and transports.',
  ),
  ...runStopBoundarySpecs.map((spec) =>
    boundary(spec.name, spec.file, [...spec.allowed], spec.reason),
  ),
  // biome-ignore format: compact declaration keeps this frozen manifest below its ceiling.
  boundary('score-boundary', 'orchestrator/src/score/score.ts', [], 'Enforce the score concern boundary.'),
  ...setupModuleSpecs.map((spec) =>
    boundary(spec.name, spec.file, [...spec.allowed], spec.reason, [...spec.typeOnlyAllowed]),
  ),
  boundary(
    'store-hooks-boundary',
    'orchestrator/src/runtime/store-hooks.ts',
    [
      '../database/db.ts',
      '../evidence/evidence-query.ts',
      '../run/run-liveness.ts',
      '../workflow/workflow-seeds.ts',
    ],
    'Enforce the store-hooks concern boundary.',
  ),
  boundary(
    'task-branch-boundary',
    'orchestrator/src/branch/task-branch.ts',
    [
      '../git/checkout-identity.ts',
      '../database/db.ts',
      '../git/git-environment.ts',
      './merged-pull-request.ts',
      '../project/projects.ts',
      '../review/review-evidence-sql.ts',
      './branch-state.ts',
      '../worktree/worktree-types.ts',
    ],
    'Keep task branch identity independent of transports, contracts, and routing.',
  ),
  boundary(
    'workflows-boundary',
    'orchestrator/src/workflow/workflow-seeds.ts',
    ['../database/db.ts', '../review/review-vocabulary.ts', './step-catalogue.ts', 'bun:sqlite'],
    'Keep workflow seeds dependent only on database transactions, review vocabulary, and catalogue validation.',
    ['./autonomy.ts'],
  ),
  boundary(
    'worktree-attribution-boundary',
    'orchestrator/src/worktree/worktree-attribution.ts',
    [
      'node:fs',
      'node:path',
      '../git/checkout-identity.ts',
      '../database/database-location.ts',
      '../database/db.ts',
      '../git/git-environment.ts',
      './worktree-types.ts',
    ],
    'Keep attribution and extraction independent of lifecycle policy and transports.',
    ['./worktree.ts'],
  ),
  boundary(
    'worktree-mcp-boundary',
    'orchestrator/src/worktree/worktree-mcp.ts',
    ['node:fs', 'node:path'],
    'Keep worker MCP file provisioning independent of lifecycle and policy.',
  ),
  boundary(
    'worktree-template-boundary',
    'orchestrator/src/worktree/worktree-template.ts',
    [],
    'Keep template grammar independent of execution, lifecycle, and policy.',
  ),
]
