import { dirname, normalize } from 'node:path'
import {
  recordReadBoundariesAfterPublish,
  recordReadBoundariesBeforePublish,
  recordSchemaBoundaries,
} from './architecture-record-boundaries.ts'

export type ImportBoundary = {
  name: string
  file: string
  allowed: string[]
  typeOnlyAllowed: string[]
  reason: string
}

const boundary = (
  name: string,
  file: string,
  allowed: string[],
  reason: string,
  typeOnlyAllowed: string[] = [],
): ImportBoundary => ({
  name,
  file,
  allowed: allowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
  typeOnlyAllowed: typeOnlyAllowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
  reason,
})

// Each row lists every import its file may use; anything else fails check-architecture.
// Widen a row deliberately, with its reason still true, rather than routing around it.
export const importBoundaries: ImportBoundary[] = [
  boundary(
    'agent-commands-boundary',
    'orchestrator/src/agent/agent-commands.ts',
    [
      './agent-probe.ts',
      './agent-registry.ts',
      '../cli/args.ts',
      '../database/db.ts',
      './model-host.ts',
    ],
    'Keep agent registry command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'canon-budget-boundary',
    'orchestrator/src/canon/canon-budget.ts',
    [],
    'Keep canon budget policy independent of every adapter and store.',
  ),
  boundary(
    'canon-commands-boundary',
    'orchestrator/src/canon/canon-commands.ts',
    [
      'node:fs',
      'node:path',
      'zod',
      './canon.ts',
      './canon-files.ts',
      './canon-hydrate.ts',
      './canon-lint.ts',
      './canon-write-gate.ts',
      '../doc/docs.ts',
      './evals.ts',
      '../project/projects.ts',
      '../../../shared/ratchet.ts',
    ],
    'Keep canon command adapters independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  boundary(
    'canon-files-boundary',
    'orchestrator/src/canon/canon-files.ts',
    ['node:fs', 'node:path', '../../../shared/git.ts', './canon-lint.ts'],
    'Keep canon file collection independent of stores, commands, runs, routing, transports, and worktrees.',
  ),
  boundary(
    'canon-hydrate-boundary',
    'orchestrator/src/canon/canon-hydrate.ts',
    ['node:path', './canon-lint.ts'],
    'Keep canon hydration planning pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'canon-lint-boundary',
    'orchestrator/src/canon/canon-lint.ts',
    [
      'node:path',
      '../../../shared/canon-references.ts',
      '../../../shared/ratchet.ts',
      './canon-budget.ts',
    ],
    'Keep canon lint decisions pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'canon-write-gate-boundary',
    'orchestrator/src/canon/canon-write-gate.ts',
    ['./canon-lint.ts'],
    'Keep canon write decisions pure and independent of filesystems, stores, commands, and processes.',
  ),
  boundary(
    'checkout-identity-boundary',
    'orchestrator/src/git/checkout-identity.ts',
    ['node:fs', 'node:path', './git-environment.ts', '../project/projects.ts'],
    'Keep checkout addressing independent of databases and lifecycle policy.',
  ),
  boundary(
    'cleanup-boundary',
    'orchestrator/src/cleanup/cleanup.ts',
    [
      'node:fs',
      'node:path',
      '../database/db.ts',
      '../resources/docker-resources.ts',
      '../evidence/evidence-query.ts',
      '../git/git-environment.ts',
      '../project/project-lock.ts',
      '../project/projects.ts',
      '../resources/resource-claims.ts',
      '../resources/resource-ownership.ts',
      '../run/run-authority.ts',
      '../worktree/worktree-attribution.ts',
      '../worktree/worktree-remove.ts',
      '../worktree/worktree-types.ts',
    ],
    'Keep cleanup independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'cleanup-sweep-boundary',
    'orchestrator/src/cleanup/cleanup-sweep.ts',
    [
      'node:fs',
      'node:path',
      './cleanup.ts',
      '../close/close-out.ts',
      '../database/db.ts',
      '../resources/docker-resources.ts',
      '../hook-tree/hook-tree.ts',
      '../../../shared/process-identity.ts',
      '../project/projects.ts',
      '../resources/resource-ownership.ts',
      '../run/run-alive.ts',
      '../run/run-artifacts.ts',
      '../run/run-authority.ts',
      '../run/run-lease.ts',
      '../worktree/worktree-attribution.ts',
      '../worktree/worktree-remove.ts',
      '../worktree/worktree-types.ts',
    ],
    'Keep cleanup-sweep independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'close-out-boundary',
    'orchestrator/src/close/close-out.ts',
    [
      'node:fs',
      'node:path',
      './close-out-adoption.ts',
      '../database/db.ts',
      '../git/git-environment.ts',
      '../hook-tree/hook-tree.ts',
      '../idle-kill.ts',
      '../worktree/keep-tree-hold.ts',
      '../../../shared/process-identity.ts',
      '../project/project-lock.ts',
      '../project/projects.ts',
      '../reclaim/reclaim.ts',
      '../resources/resource-claims.ts',
      '../resources/resource-ownership.ts',
      '../run/run-alive.ts',
      '../run/run-artifacts.ts',
      '../run/run-lease.ts',
      '../run/run-process.ts',
      '../worktree/worktree.ts',
      '../worktree/worktree-attribution.ts',
      '../worktree/worktree-remove.ts',
      '../worktree/worktree-types.ts',
    ],
    'Keep close-out independent of routing, contracts, transports, reviews, and the CLI.',
  ),
  boundary(
    'confinement-ruling-boundary',
    'orchestrator/src/confinement/confinement-ruling.ts',
    [
      'node:fs',
      './confinement.ts',
      '../database/db.ts',
      '../git/git-environment.ts',
      '../project/projects.ts',
      '../run/run-authority.ts',
      '../run/run-liveness.ts',
    ],
    'Keep confinement rulings independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'contract-boundary',
    'orchestrator/src/contract/contract.ts',
    ['../jobs/jobs.ts', '../outcome.ts', '../review/review-vocabulary.ts', '../run/checkpoint.ts'],
    'Keep reply dialect resolution independent of lifecycle and impure transport concerns.',
  ),
  boundary(
    'database-boundary',
    'orchestrator/src/database/db.ts',
    [
      'bun:sqlite',
      'node:crypto',
      'node:fs',
      'node:path',
      'node:url',
      '../../../shared/brand.ts',
      './contention.ts',
      './database-location.ts',
      './migrations.ts',
    ],
    'Enforce the database concern boundary.',
  ),
  boundary(
    'dispatch-commands-boundary',
    'orchestrator/src/dispatch/dispatch-commands.ts',
    [
      'node:fs',
      './dispatch-preflight.ts',
      './review-lens-prompt.ts',
      '../jobs/jobs.ts',
      '../worktree/keep-tree-hold.ts',
      '../project/projects.ts',
      '../route/failover.ts',
      '../mcp/mcp-preflight.ts',
    ],
    'Keep dispatch command adapters independent of transports, routing, worktrees, the CLI, and reviews.',
  ),
  boundary(
    'dispatch-preflight-boundary',
    'orchestrator/src/dispatch/dispatch-preflight.ts',
    [
      '../cli/args.ts',
      '../git/checkout-identity.ts',
      '../database/db.ts',
      '../git/git-environment.ts',
      '../jobs/jobs.ts',
      '../lens/lenses.ts',
      '../project/projects.ts',
      '../review/review-target.ts',
      '../worktree/worktree-caller.ts',
      '../worktree/worktree-preflight.ts',
      '../worktree/worktree-template.ts',
    ],
    'Keep dispatch admission independent of transports, routing, and contracts.',
  ),
  boundary(
    'review-lens-prompt-boundary',
    'orchestrator/src/dispatch/review-lens-prompt.ts',
    [],
    'Keep review-lens prompt composition a pure decision over lens text and supplied prompt.',
  ),
  boundary(
    'doc-commands-boundary',
    'orchestrator/src/doc/doc-commands.ts',
    ['node:fs', '../canon/canon.ts', './docs.ts'],
    'Keep doc commands independent of database writes beyond docs, runs, routing, transports, and the CLI.',
  ),
  boundary(
    'doc-write-allowed-boundary',
    'orchestrator/src/doc/doc-write-allowed.ts',
    [
      '../canon/canon-hydrate.ts',
      '../canon/canon-write-gate.ts',
      '../canon/pack-budget.ts',
      '../canon/canon-lint.ts',
    ],
    'Keep document write decisions independent of stores, HTTP, filesystems, and CLI.',
  ),
  boundary(
    'doctor-boundary',
    'orchestrator/src/health/doctor.ts',
    [
      'node:fs',
      '../agent/agent-auth.ts',
      '../agent/agent-registry.ts',
      '../agent/agents.ts',
      '../score/agreement.ts',
      '../database/db.ts',
      '../resources/docker-resources.ts',
      '../evidence/evidence-query.ts',
      '../worktree/keep-tree-hold.ts',
      '../agent/model-host.ts',
      '../resources/resource-claims.ts',
      '../resources/resource-ownership.ts',
      '../score/score.ts',
      '../worktree/worktree-attribution.ts',
      '../worktree/worktree-lifecycle.ts',
      '../canon/canon.ts',
      '../doc/docs.ts',
      '../canon/pack-budget.ts',
      '../canon/evals.ts',
      '../sandbox/sandbox.ts',
      '../database/migrations.ts',
      './health.ts',
      '../project/projects.ts',
    ],
    'Keep doctor independent of transports, routing, run control, the CLI, and reviews by value.',
  ),
  boundary(
    'duel-boundary',
    'orchestrator/src/score/duel.ts',
    ['../database/db.ts', '../evidence/evidence-query.ts', './score.ts'],
    'Enforce the duel concern boundary.',
  ),
  boundary(
    'epic-commands-boundary',
    'orchestrator/src/epic/epic-commands.ts',
    ['./epic.ts'],
    'Keep epic command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'evidence-boundary',
    'orchestrator/src/evidence/evidence.ts',
    ['../contract/contract.ts', '../mcp/mcp-preflight.ts', '../review/review-triage.ts'],
    'Keep evidence assessment independent of execution and transaction ownership.',
    ['bun:sqlite', '../review/review.ts'],
  ),
  boundary(
    'evidence-query-boundary',
    'orchestrator/src/evidence/evidence-query.ts',
    ['../database/db.ts', '../failure/failure.ts', '../hook-tree/hook-tree.ts', 'bun:sqlite'],
    'Enforce the evidence-query concern boundary.',
  ),
  boundary(
    'failover-boundary',
    'orchestrator/src/route/failover.ts',
    [
      '../agent/agent-registry.ts',
      '../database/db.ts',
      'bun:sqlite',
      '../worktree/keep-tree-hold.ts',
      '../mcp/mcp-preflight.ts',
      '../run/resume-tree.ts',
    ],
    'Keep failover independent of execution transports, contracts, and worktrees.',
  ),
  boundary(
    'failure-commands-boundary',
    'orchestrator/src/failure/failure-commands.ts',
    ['../database/db.ts', './failure.ts', '../run/run-authority.ts'],
    'Keep failure command adapters independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  boundary(
    'git-environment-boundary',
    'orchestrator/src/git/git-environment.ts',
    ['node:crypto', 'node:fs', 'node:os', 'node:path', '../../../shared/git.ts'],
    'Keep hermetic git observation independent of lifecycle and policy concerns.',
  ),
  boundary(
    'health-commands-boundary',
    'orchestrator/src/health/health-commands.ts',
    ['../../../shared/orch-contract.ts', '../database/db.ts', './health.ts'],
    'Keep health command adapters independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  boundary(
    'hosted-hub-server-boundary',
    'hub/src/hosted.ts',
    [
      'node:fs',
      'node:url',
      '@trpc/server/adapters/fetch',
      './app-static.ts',
      './evidence-api.ts',
      './hosted-health.ts',
      './note-api.ts',
      './report-api.ts',
      './task-api.ts',
      './trpc/context.ts',
      './trpc/hosted-router.ts',
    ],
    'Enforce the hosted hub server concern boundary.',
  ),
  boundary(
    'isolation-boundary',
    'orchestrator/src/worktree/worktree.ts',
    [
      'node:fs',
      './worktree-create.ts',
      './worktree-readonly.ts',
      '../project/projects.ts',
      './worktree-types.ts',
    ],
    'Keep the isolation module independent of run policy and lifecycle concerns.',
  ),
  boundary(
    'issue-report-fields-boundary',
    'orchestrator/src/issue/issue-report-fields.ts',
    [],
    'Keep issue report field decisions pure and independent of adapters.',
  ),
  boundary(
    'job-commands-boundary',
    'orchestrator/src/jobs/job-commands.ts',
    ['./jobs.ts'],
    'Keep job catalogue command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'judgement-boundary',
    'orchestrator/src/judgement.ts',
    [
      'node:fs',
      '../../shared/record/schema.ts',
      './database/db.ts',
      './score/duel.ts',
      './jobs/jobs.ts',
      './record/machine-identity.ts',
      './record/record-api-client.ts',
      './review/review.ts',
      './review/review-outbox.ts',
      './review/review-triage.ts',
      './review/review-vocabulary.ts',
      './run/run-authority.ts',
      './run/run-outbox.ts',
      './score/score.ts',
    ],
    'Keep judgement independent of transports, worktrees, routing, the CLI, durable execution, dispatch, and cleanup.',
  ),
  boundary(
    'landing-outbox-boundary',
    'orchestrator/src/record/landing-outbox.ts',
    ['../../../shared/record/schema.ts', 'bun:sqlite'],
    'Enforce the landing-outbox concern boundary.',
  ),
  boundary(
    'machine-identity-boundary',
    'orchestrator/src/record/machine-identity.ts',
    ['node:os', '../../../shared/record/schema.ts', '../database/db.ts'],
    'Enforce the machine-identity concern boundary.',
  ),
  boundary(
    'mcp-commands-boundary',
    'orchestrator/src/mcp/mcp-commands.ts',
    ['./mcp.ts'],
    'Keep MCP command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'mcp-preflight-boundary',
    'orchestrator/src/mcp/mcp-preflight.ts',
    [
      '../agent/agent-registry.ts',
      '../jobs/jobs.ts',
      '../project/projects.ts',
      '../run/run-process.ts',
    ],
    'Keep MCP preflight independent of execution, transport, routing, and mutation.',
    ['../contract/contract.ts'],
  ),
  boundary(
    'metric-commands-boundary',
    'orchestrator/src/metric/metric-commands.ts',
    ['./metric.ts'],
    'Keep metric command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'monitor-commands-boundary',
    'orchestrator/src/monitor/monitor-commands.ts',
    [
      'node:crypto',
      'node:fs',
      'node:path',
      '../../../shared/install-root.ts',
      '../../../shared/monitor-capability.ts',
      '../../../shared/process-identity.ts',
      '../database/db.ts',
      '../canon/evals.ts',
      './monitor.ts',
      './monitor-notices.ts',
      './monitor-types.ts',
    ],
    'Keep monitor command adapters independent of the run nucleus and the CLI: they compose concern modules for one verb and own no lifecycle.',
  ),
  boundary(
    'outcome-boundary',
    'orchestrator/src/outcome.ts',
    [],
    'Keep outcome decisions and interpretation independent of lifecycle concerns.',
  ),
  boundary(
    'port-commands-boundary',
    'orchestrator/src/porting/port-commands.ts',
    [
      'node:fs',
      'node:path',
      '../database/db.ts',
      './porting.ts',
      './porting-import.ts',
      '../project/projects.ts',
    ],
    'Keep port commands independent of runs, routing, transports, the CLI, and worktrees.',
  ),
  ...recordSchemaBoundaries,
  boundary(
    'project-commands-boundary',
    'orchestrator/src/project/project-commands.ts',
    [
      'node:fs',
      '../database/db.ts',
      '../lens/lenses.ts',
      './projects.ts',
      '../worktree/worktree-lifecycle.ts',
      '../worktree/worktree-template.ts',
    ],
    'Keep project commands independent of runs, routing, transports, reviews, the CLI, and worktrees by value.',
  ),
  boundary(
    'prompt-retarget-boundary',
    'orchestrator/src/dispatch/prompt-retarget.ts',
    ['../git/checkout-identity.ts'],
    'Keep prompt retargeting independent of database, transport, contract, and routing concerns.',
  ),
  boundary(
    'recalibration-boundary',
    'orchestrator/src/score/recalibration.ts',
    [
      'node:fs',
      'node:readline/promises',
      './agreement.ts',
      '../database/db.ts',
      '../jobs/jobs.ts',
      './score.ts',
      'node:stream',
    ],
    'Keep recalibration independent of transports, worktrees, routing, the CLI, durable execution, dispatch, and cleanup.',
  ),
  boundary(
    'recipe-lifecycle-boundary',
    'orchestrator/src/recipe/recipe-lifecycle.ts',
    ['./recipe-schema.ts', './recipe-step.ts'],
    'Keep lifecycle planning pure and independent of execution, persistence, filesystem, and the register.',
  ),
  boundary(
    'recipe-loader-boundary',
    'orchestrator/src/recipe/recipe-loader.ts',
    ['node:fs', 'node:path', './recipe-schema.ts'],
    'Keep tracked recipe loading independent of execution, persistence, and CLI concerns.',
  ),
  boundary(
    'recipe-schema-boundary',
    'orchestrator/src/recipe/recipe-schema.ts',
    ['zod'],
    'Keep the recipe schema pure and independent of file, register, and execution concerns.',
  ),
  boundary(
    'recipe-step-boundary',
    'orchestrator/src/recipe/recipe-step.ts',
    ['node:path', '../worktree/worktree-template.ts', './recipe-schema.ts'],
    'Keep recipe step execution independent of lifecycle, persistence, claims, and register concerns.',
  ),
  boundary(
    'record-api-boundary',
    'orchestrator/src/record/record-api.ts',
    [
      'hono',
      'hono/cors',
      'zod',
      './record-config.ts',
      './record-auth.ts',
      './record-docs.ts',
      './record-snapshots.ts',
      './record-verdicts.ts',
      './record-projects.ts',
      './record-runs.ts',
    ],
    'Enforce the record-api concern boundary.',
  ),
  boundary(
    'record-api-client-boundary',
    'orchestrator/src/record/record-api-client.ts',
    [
      '../doc/doc-write-allowed.ts',
      './record-auth.ts',
      './record-session.ts',
      './record-snapshots.ts',
    ],
    'Enforce the record API client concern boundary.',
  ),
  boundary(
    'record-api-server-boundary',
    'orchestrator/src/record/record-api-server.ts',
    [
      '../postgres/postgres-migrate.ts',
      './record-config.ts',
      './record-api.ts',
      './record-auth.ts',
      './record-docs.ts',
      './record-projects.ts',
      './record-reviews.ts',
      './record-runs.ts',
      './record-snapshots.ts',
      './record-verdicts.ts',
    ],
    'Enforce the record-api-server concern boundary.',
  ),
  boundary(
    'record-auth-command-boundary',
    'orchestrator/src/record/record-auth-command.ts',
    ['../../../shared/record-session.ts', './record-auth.ts', './record-session.ts'],
    'Enforce the record-auth-command concern boundary.',
  ),
  boundary(
    'record-cache-boundary',
    'orchestrator/src/record/record-cache.ts',
    ['../database/db.ts', './record-api-client.ts', 'bun:sqlite'],
    'Enforce the record-cache concern boundary.',
  ),
  ...recordReadBoundariesBeforePublish,
  boundary(
    'record-publish-boundary',
    'orchestrator/src/record/record-publish.ts',
    [
      '../agent/agent-commands.ts',
      '../health/health-commands.ts',
      '../jobs/job-commands.ts',
      './machine-identity.ts',
      './record-api-client.ts',
      './record-snapshots.ts',
      '../state/serve.ts',
    ],
    'Enforce that snapshot publishing composes only the existing view services and record client.',
  ),
  boundary(
    'record-push-docs-boundary',
    'orchestrator/src/record/record-push-docs.ts',
    ['../database/db.ts', './record-api-client.ts', '../doc/doc-write-allowed.ts'],
    'Enforce the record-push-docs concern boundary.',
  ),
  ...recordReadBoundariesAfterPublish,
  boundary(
    'record-sync-boundary',
    'orchestrator/src/record/record-sync.ts',
    [
      'bun',
      'drizzle-orm/bun-sql',
      '../../../shared/record/schema.ts',
      '../../../shared/record/schema-landing.ts',
      '../../../shared/record/schema-review.ts',
      '../../../shared/record/schema-run.ts',
      '../database/db.ts',
      './landing-outbox.ts',
      './machine-identity.ts',
      './record-cache.ts',
      './record-session.ts',
      '../review/review-outbox.ts',
      '../run/run-outbox.ts',
      '../score/score-outbox.ts',
      'bun:sqlite',
    ],
    'Enforce the record-sync concern boundary.',
  ),
  boundary(
    'record-sync-command-boundary',
    'orchestrator/src/record/record-sync-command.ts',
    ['./record-sync.ts'],
    'Enforce the record-sync-command concern boundary.',
  ),
  boundary(
    'record-verdicts-boundary',
    'orchestrator/src/record/record-verdicts.ts',
    ['bun', '../score/score.ts'],
    'Enforce the record-verdicts concern boundary.',
  ),
  boundary(
    'resource-ownership-boundary',
    'orchestrator/src/resources/resource-ownership.ts',
    [
      'node:fs',
      'node:path',
      '../git/checkout-identity.ts',
      '../database/database-location.ts',
      '../database/db.ts',
      './docker-resources.ts',
      '../evidence/evidence-query.ts',
      '../git/git-environment.ts',
      '../../../shared/process-identity.ts',
      '../project/project-lock.ts',
      '../run/run-alive.ts',
      '../run/run-lease.ts',
      'bun:sqlite',
    ],
    'Enforce the resource-ownership concern boundary.',
  ),
  boundary(
    'review-boundary',
    'orchestrator/src/review/review.ts',
    [
      '../../../shared/record/schema.ts',
      '../database/db.ts',
      './review-outbox.ts',
      '../contract/contract.ts',
      '../jobs/jobs.ts',
      './review-coverage.ts',
      './review-coverage-match.ts',
      './review-pins.ts',
      './review-tier.ts',
    ],
    'Keep review verdicts independent of landing policy and run-chain ownership.',
    ['bun:sqlite', './review-types.ts'],
  ),
  boundary(
    'review-commands-boundary',
    'orchestrator/src/review/review-commands.ts',
    [
      'bun:sqlite',
      'node:fs',
      'zod',
      '../database/db.ts',
      '../git/git-environment.ts',
      '../jobs/jobs.ts',
      '../project/projects.ts',
      './review.ts',
      './review-calibration.ts',
      './review-coverage.ts',
      './review-evidence-sql.ts',
      './review-pins.ts',
      './review-tier.ts',
      './review-triage.ts',
      './review-vocabulary.ts',
      './review-yield.ts',
    ],
    'Keep review commands independent of runs, transports, routing by value, the CLI, and worktrees by value.',
  ),
  boundary(
    'review-outbox-boundary',
    'orchestrator/src/review/review-outbox.ts',
    ['../../../shared/record/schema.ts', '../database/db.ts', 'bun:sqlite'],
    'Enforce the review-outbox concern boundary.',
  ),
  boundary(
    'review-target-boundary',
    'orchestrator/src/review/review-target.ts',
    [
      'node:path',
      '../git/git-environment.ts',
      '../project/projects.ts',
      '../worktree/worktree-caller.ts',
    ],
    'Keep review-target resolution independent of execution and mutation concerns.',
  ),
  boundary(
    'review-vocabulary-boundary',
    'orchestrator/src/review/review-vocabulary.ts',
    [],
    'Enforce the review-vocabulary concern boundary.',
  ),
  boundary(
    'routing-commands-boundary',
    'orchestrator/src/route/routing-commands.ts',
    [
      '../score/agreement.ts',
      '../score/duel.ts',
      '../state/guide.ts',
      '../lens/lenses.ts',
      '../project/projects.ts',
      './route.ts',
      './routing-backtest.ts',
    ],
    'Keep routing command adapters independent of runs, transports, the CLI, worktrees, and reviews by value.',
  ),
  boundary(
    'run-answer-boundary',
    'orchestrator/src/run/run-answer.ts',
    [
      'node:fs',
      '../../../shared/process-identity.ts',
      '../agent/agent-registry.ts',
      '../cli/args.ts',
      '../contract/contract.ts',
      '../database/db.ts',
      '../route/failover.ts',
      '../jobs/jobs.ts',
      '../worktree/keep-tree-hold.ts',
      '../mcp/mcp-preflight.ts',
      '../outcome.ts',
      './run.ts',
      './run-artifacts.ts',
      './run-authority.ts',
      './run-control.ts',
      './run-dispatch.ts',
      '../git/git-environment.ts',
    ],
    'Keep run-answer independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-artifacts-boundary',
    'orchestrator/src/run/run-artifacts.ts',
    [
      'node:fs',
      'node:path',
      '../artifact-paths.ts',
      '../database/database-location.ts',
      '../database/db.ts',
      '../database/migrations.ts',
      '../resources/resource-ownership.ts',
    ],
    'Keep run artifacts independent of routing, contracts, transports, reviews, and isolation.',
  ),
  boundary(
    'run-authority-boundary',
    'orchestrator/src/run/run-authority.ts',
    ['../database/db.ts', 'bun:sqlite'],
    'Enforce the run-authority concern boundary.',
  ),
  boundary(
    'run-control-boundary',
    'orchestrator/src/run/run-control.ts',
    [
      'node:fs',
      '../cli/args.ts',
      '../clock.ts',
      '../collect/collect.ts',
      '../database/db.ts',
      '../events.ts',
      '../route/failover.ts',
      '../git/git-environment.ts',
      '../mcp/mcp-preflight.ts',
      '../outcome.ts',
      '../project/projects.ts',
      './resume-tree.ts',
      './run.ts',
      './run-authority.ts',
      './run-dispatch.ts',
      './run-liveness.ts',
      './checkpoint.ts',
    ],
    'Keep run-control independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-diff-boundary',
    'orchestrator/src/run/run-diff.ts',
    ['node:fs', '../database/db.ts', '../git/git-environment.ts', '../project/projects.ts'],
    'Keep run diff independent of run control, transports, routing, the CLI, and worktrees by value.',
  ),
  boundary(
    'run-dispatch-boundary',
    'orchestrator/src/run/run-dispatch.ts',
    [
      'node:child_process',
      'node:crypto',
      'node:fs',
      '../../../shared/install-root.ts',
      '../database/db.ts',
      '../dispatch/dispatch-preflight.ts',
      '../jobs/jobs.ts',
      '../mcp/mcp-preflight.ts',
      '../project/projects.ts',
      '../record/record-attribution.ts',
      './run.ts',
      './run-artifacts.ts',
      '../route/failover.ts',
    ],
    'Keep run-dispatch independent of transports, worktrees, routing, reviews, and the CLI.',
  ),
  boundary(
    'run-inbox-boundary',
    'orchestrator/src/run/run-inbox.ts',
    ['../database/db.ts', '../evidence/evidence-query.ts', '../project/projects.ts'],
    'Keep run inbox independent of run control, transports, routing, the CLI, and worktrees.',
  ),
  boundary(
    'run-listing-boundary',
    'orchestrator/src/run/run-listing.ts',
    [
      '../collect/collect.ts',
      '../database/db.ts',
      '../evidence/evidence-query.ts',
      '../outcome.ts',
      '../events.ts',
      '../idle-kill.ts',
    ],
    'Keep run listing independent of run control, transports, routing, the CLI, and worktrees.',
  ),
  boundary(
    'run-liveness-boundary',
    'orchestrator/src/run/run-liveness.ts',
    [
      '../database/db.ts',
      '../../../shared/process-identity.ts',
      '../resources/resource-ownership.ts',
      './run-alive.ts',
      './run-authority.ts',
      './run-lease.ts',
      'bun:sqlite',
    ],
    'Enforce the run-liveness concern boundary.',
  ),
  boundary(
    'run-outbox-boundary',
    'orchestrator/src/run/run-outbox.ts',
    ['../../../shared/record/schema.ts', '../hook-tree/hook-tree.ts', 'bun:sqlite'],
    'Enforce the run-outbox concern boundary.',
  ),
  boundary(
    'run-process-boundary',
    'orchestrator/src/run/run-process.ts',
    [
      'node:crypto',
      './checkpoint.ts',
      '../database/db.ts',
      '../dispatch/dispatch-preflight.ts',
      '../idle-kill.ts',
      '../agent/agent-registry.ts',
    ],
    'Keep run process control independent of routing, contracts, reviews, and transports.',
  ),
  boundary(
    'run-stop-boundary',
    'orchestrator/src/run/run-stop.ts',
    [
      '../cleanup/cleanup.ts',
      '../database/db.ts',
      '../resources/resource-ownership.ts',
      './run-authority.ts',
      './run-liveness.ts',
      '../worktree/worktree-remove.ts',
      '../worktree/worktree-types.ts',
    ],
    'Keep run-stop independent of transports, routing, reviews, contracts, the CLI, and durable execution.',
  ),
  boundary(
    'score-boundary',
    'orchestrator/src/score/score.ts',
    [],
    'Enforce the score concern boundary.',
  ),
  boundary(
    'store-hooks-boundary',
    'orchestrator/src/runtime/store-hooks.ts',
    [
      '../database/db.ts',
      '../evidence/evidence-query.ts',
      '../run/run-liveness.ts',
      '../workflow/workflow-seeds.ts',
    ],
    'Enforce the store-hooks concern boundary.',
  ),
  boundary(
    'task-branch-boundary',
    'orchestrator/src/branch/task-branch.ts',
    [
      '../git/checkout-identity.ts',
      '../database/db.ts',
      '../git/git-environment.ts',
      './merged-pull-request.ts',
      '../project/projects.ts',
      '../review/review-evidence-sql.ts',
      './branch-state.ts',
      '../worktree/worktree-types.ts',
    ],
    'Keep task branch identity independent of transports, contracts, and routing.',
  ),
  boundary(
    'workflows-boundary',
    'orchestrator/src/workflow/workflow-seeds.ts',
    ['../database/db.ts', '../review/review-vocabulary.ts', 'bun:sqlite'],
    'Keep workflow seeds dependent only on database transactions and review vocabulary.',
  ),
  boundary(
    'worktree-attribution-boundary',
    'orchestrator/src/worktree/worktree-attribution.ts',
    [
      'node:fs',
      'node:path',
      '../git/checkout-identity.ts',
      '../database/database-location.ts',
      '../database/db.ts',
      '../git/git-environment.ts',
      './worktree-types.ts',
    ],
    'Keep attribution and extraction independent of lifecycle policy and transports.',
    ['./worktree.ts'],
  ),
  boundary(
    'worktree-mcp-boundary',
    'orchestrator/src/worktree/worktree-mcp.ts',
    ['node:fs', 'node:path'],
    'Keep worker MCP file provisioning independent of lifecycle and policy.',
  ),
  boundary(
    'worktree-template-boundary',
    'orchestrator/src/worktree/worktree-template.ts',
    [],
    'Keep template grammar independent of execution, lifecycle, and policy.',
  ),
]
