// concern: architecture-manifest
/** The hosted-record command module allowlists, kept beside the root manifest so it stays within its file ceiling. */
import { dirname, normalize } from 'node:path'

type RecordModule = { file: string; allowed: string[] }

const module = (file: string, allowed: string[]): RecordModule => ({
  file,
  allowed: allowed.map((target) =>
    target.startsWith('.') ? normalize(`${dirname(file)}/${target}`) : target,
  ),
})

export const recordModules: RecordModule[] = [
  module('orchestrator/src/record/record-doc-import-write.ts', ['bun', './record-doc-mapping.ts']),
  module('orchestrator/src/record/record-doc-status.ts', [
    '../../../shared/docs.ts',
    './record-doc-errors.ts',
  ]),
  module('orchestrator/src/record/install-binding.ts', ['bun:sqlite', '../database/db.ts']),
  module('orchestrator/src/record/record-write-decision.ts', []),
  module('orchestrator/src/record/record-write-authority.ts', [
    '../../../shared/record-api-url.ts',
    './install-binding.ts',
    './record-write-decision.ts',
  ]),
  module('orchestrator/src/run/question-delivery.ts', [
    '../database/db.ts',
    './question-vocabulary.ts',
  ]),
  module('orchestrator/src/run/question-outbox.ts', [
    'bun:sqlite',
    '../../../shared/record/schema.ts',
    '../database/db.ts',
    '../record/outbox-sanitize.ts',
  ]),
  module('orchestrator/src/record/outbox-sanitize.ts', ['../../../shared/secret-shaped.ts']),
  module('orchestrator/src/record/outbox-secret-audit.ts', ['bun:sqlite', './outbox-sanitize.ts']),
  module('orchestrator/src/record/outbox-redaction.ts', [
    'bun:sqlite',
    '../database/db.ts',
    './outbox-sanitize.ts',
  ]),
  module('orchestrator/src/record/record-command.ts', [
    '../../../shared/machine-config.ts',
    '../database/db.ts',
    '../postgres/postgres-migrate.ts',
    '../project/projects.ts',
    './outbox-secret-audit.ts',
    './outbox-redaction.ts',
    './record-doctor.ts',
    './record-space-move.ts',
    './record-space.ts',
    './record-tunnel-error.ts',
  ]),
  module('orchestrator/src/record/record-tunnel-error.ts', []),
  module('orchestrator/src/record/record-release-check.ts', [
    '../postgres/postgres-migrate.ts',
    './record-release-decision.ts',
  ]),
  module('orchestrator/src/record/record-release-decision.ts', []),
  module('orchestrator/src/record/record-attribution.ts', [
    'bun:sqlite',
    '../../../shared/record-api-url.ts',
    '../database/db.ts',
    './record-api-client.ts',
    './record-session.ts',
  ]),
  module('orchestrator/src/record/record-doctor.ts', [
    '../postgres/postgres-migrate.ts',
    '../database/db.ts',
    '../../../shared/record/schema.ts',
    './record-attribution.ts',
    './record-auth.ts',
    './record-session.ts',
    './record-sync.ts',
    './install-binding.ts',
    './machine-identity.ts',
    './outbox-dependency.ts',
    './outbox-quarantine.ts',
  ]),
  module('orchestrator/src/record/outbox-failure.ts', ['./record-verdicts.ts']),
  module('orchestrator/src/record/outbox-dependency.ts', ['bun:sqlite', './record-sync-types.ts']),
  module('orchestrator/src/record/outbox-operator.ts', [
    'bun:sqlite',
    '../database/db.ts',
    './outbox-dependency.ts',
    './outbox-quarantine.ts',
  ]),
  module('orchestrator/src/record/outbox-quarantine.ts', ['bun:sqlite', '../database/db.ts']),
  module('orchestrator/src/record/outbox-payload-contracts.ts', [
    '../review/review-outbox.ts',
    '../run/question-outbox.ts',
    '../run/run-outbox.ts',
    '../score/score-outbox.ts',
    './landing-outbox.ts',
  ]),
  module('orchestrator/src/record/record-session.ts', [
    '../../../shared/record-session.ts',
    '../../../shared/record-remedies.ts',
    '../database/db.ts',
    './record-auth.ts',
  ]),
  module('orchestrator/src/record/record-space.ts', [
    '../../../shared/record/schema.ts',
    './record-api-client.ts',
    './record-auth.ts',
    './record-session.ts',
  ]),
  module('orchestrator/src/record/record-invitation.ts', []),
  module('orchestrator/src/record/record-api-access.ts', ['hono']),
  module('orchestrator/src/record/record-api-public-docs.ts', [
    'hono',
    'hono/bun',
    'hono-rate-limiter',
    'zod',
    '../../../shared/docs.ts',
    './record-public-docs.ts',
  ]),
  module('orchestrator/src/record/record-public-docs.ts', [
    'bun',
    '../../../shared/docs.ts',
    '../../../shared/record/tenant.ts',
  ]),
  module('orchestrator/src/record/record-doc-errors.ts', ['../doc/doc-write-allowed.ts']),
  module('orchestrator/src/record/record-api-settings.ts', [
    'hono',
    'zod',
    './record-auth.ts',
    './record-settings.ts',
  ]),
  module('orchestrator/src/record/record-settings.ts', [
    '../doc/doc-write-allowed.ts',
    '../settings/settings.ts',
    '../settings/settings-permission.ts',
    './record-docs.ts',
  ]),
  module('orchestrator/src/record/record-space-move.ts', [
    'bun',
    '../postgres/postgres-migrate.ts',
    './record-session.ts',
    './record-space.ts',
  ]),
  module('orchestrator/src/record/record-board-contract.ts', []),
  module('orchestrator/src/record/record-board-scope.ts', [
    '../board/board-policy.ts',
    '../board/board-tags.ts',
    './record-board-contract.ts',
  ]),
  module('orchestrator/src/record/record-board-tx.ts', [
    'bun',
    '../../../shared/record/tenant.ts',
    './record-board-contract.ts',
  ]),
  module('orchestrator/src/record/record-board-messages.ts', [
    'bun',
    '../../../shared/secret-shaped.ts',
    '../board/board-policy.ts',
    '../board/board-tags.ts',
    '../board/board-thread-policy.ts',
    './record-board-contract.ts',
    './record-board-scope.ts',
    './record-board-tx.ts',
  ]),
  module('orchestrator/src/record/record-board-receipts.ts', [
    './record-board-contract.ts',
    './record-board-messages.ts',
    './record-board-tx.ts',
  ]),
  module('orchestrator/src/record/record-board-changes.ts', [
    '../board/board-tags.ts',
    './record-board-contract.ts',
    './record-board-messages.ts',
    './record-board-receipts.ts',
    './record-board-tx.ts',
  ]),
  module('orchestrator/src/record/record-board-overview.ts', [
    'bun',
    '../board/board-tags.ts',
    './record-board-contract.ts',
    './record-board-messages.ts',
    './record-board-receipts.ts',
    './record-board-tx.ts',
  ]),
  module('orchestrator/src/record/record-board-claims.ts', [
    'bun',
    '../../../shared/record/schema.ts',
    '../board/board-claim-policy.ts',
    '../board/board-policy.ts',
    './record-board-contract.ts',
    './record-board-messages.ts',
    './record-board-scope.ts',
    './record-board-tx.ts',
  ]),
  module('orchestrator/src/record/record-api-board.ts', [
    'hono',
    'zod',
    './record-auth.ts',
    './record-board-contract.ts',
    './record-board-tx.ts',
  ]),
]
