// concern: postgres-schema-run
/** Knows the hosted run record shape. Must not know local execution state or synchronization. */
import { sql } from 'drizzle-orm'
import {
  type AnyPgColumn,
  bigint,
  boolean,
  check,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core'
import { machine, project, spaceIdentity, tenantPolicies, user } from './schema.ts'

export const run = pgTable.withRLS(
  'run',
  {
    id: uuid().primaryKey(),
    spaceId: spaceIdentity(),
    projectId: uuid('project_id').references(() => project.id),
    machineId: uuid('machine_id')
      .notNull()
      .references(() => machine.id),
    localId: bigint('local_id', { mode: 'bigint' }).notNull(),
    startedByUserId: uuid('started_by_user_id').references(() => user.id),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
    agent: text().notNull(),
    job: text().notNull(),
    promptSha: text('prompt_sha').notNull(),
    specSha: text('spec_sha'),
    promptBytes: bigint('prompt_bytes', { mode: 'bigint' }).notNull(),
    promptHead: text('prompt_head').notNull(),
    taskKey: text('task_key'),
    label: text(),
    lens: text(),
    latencyMs: bigint('latency_ms', { mode: 'bigint' }),
    exitCode: integer('exit_code'),
    outputBytes: bigint('output_bytes', { mode: 'bigint' }),
    vendorTokens: bigint('vendor_tokens', { mode: 'bigint' }),
    vendorCostUsd: doublePrecision('vendor_cost_usd'),
    probe: boolean().notNull(),
    failureKind: text('failure_kind'),
    status: text().notNull(),
    error: text(),
    retryOf: uuid('retry_of').references((): AnyPgColumn => run.id),
    parentRunId: uuid('parent_run_id').references((): AnyPgColumn => run.id),
    turn: integer().notNull(),
    filesChanged: integer('files_changed'),
    changedPaths: jsonb('changed_paths'),
    linesAdded: integer('lines_added'),
    linesRemoved: integer('lines_removed'),
    testsRan: integer('tests_ran'),
    testsPassed: integer('tests_passed'),
    deviations: integer(),
    escalations: integer(),
    stack: text(),
    model: text(),
    evidenceExcluded: text('evidence_excluded'),
    inputTree: text('input_tree'),
    headCommit: text('head_commit'),
    reviewRef: text('review_ref'),
    branch: text(),
    baseCommit: text('base_commit'),
    mintedBranch: text('minted_branch'),
    docsInjected: integer('docs_injected'),
    docRevisions: jsonb('doc_revisions'),
    canonSha: text('canon_sha'),
    transport: text(),
    sessionId: text('session_id'),
    routeReason: text('route_reason'),
    noFailover: boolean('no_failover').notNull(),
    automaticFailover: boolean('automatic_failover').notNull(),
    outsideWorktreeWrites: jsonb('outside_worktree_writes'),
    reviewProvenance: jsonb('review_provenance'),
    provenanceStatus: text('provenance_status'),
    workPreserved: boolean('work_preserved').notNull(),
    closeOutOutcome: text('close_out_outcome'),
    closeOutDetail: text('close_out_detail'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
  },
  (table) => [
    unique('run_machine_local_unique').on(table.machineId, table.localId),
    index('run_space_started_id_idx').on(table.spaceId, table.startedAt.desc(), table.id.desc()),
    ...tenantPolicies('run', table.spaceId),
  ],
)

export const runScore = pgTable.withRLS(
  'run_score',
  {
    runId: uuid('run_id').primaryKey(),
    spaceId: spaceIdentity(),
    delivery: text().notNull(),
    quality: text(),
    fidelity: text(),
    note: text(),
    scoredAt: timestamp('scored_at', { withTimezone: true }).notNull(),
    scoredBy: text('scored_by').notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
  },
  (table) => [
    check('run_score_delivery_check', sql`${table.delivery} IN ('none', 'partial', 'full')`),
    check(
      'run_score_quality_check',
      sql`${table.quality} IS NULL OR ${table.quality} IN ('wrong', 'mixed', 'right')`,
    ),
    check(
      'run_score_fidelity_check',
      sql`${table.fidelity} IS NULL OR ${table.fidelity} IN ('drifted', 'partial', 'faithful')`,
    ),
    check(
      'run_score_delivery_quality_check',
      sql`(${table.delivery} = 'none') = (${table.quality} IS NULL)`,
    ),
    ...tenantPolicies('run_score', table.spaceId),
  ],
)

/** Survives a void issued before the run row exists so a later run upsert cannot drop it. */
export const runExclusion = pgTable.withRLS(
  'run_exclusion',
  {
    runId: uuid('run_id').primaryKey(),
    spaceId: spaceIdentity(),
    reason: text().notNull(),
    excludedAt: timestamp('excluded_at', { withTimezone: true }).notNull(),
  },
  (table) => [...tenantPolicies('run_exclusion', table.spaceId)],
)
